# Generated by Django 4.1.7 on 2023-03-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("email", models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=20, null=True)),
                ("airbyte_workspace_id", models.CharField(max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrgDbt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gitrepo_url", models.CharField(max_length=100)),
                ("project_dir", models.CharField(max_length=200)),
                ("dbtversion", models.CharField(max_length=10)),
                ("targetname", models.CharField(max_length=10)),
                ("targettype", models.CharField(max_length=10)),
                ("targetschema", models.CharField(max_length=10)),
                ("host", models.CharField(max_length=100)),
                ("port", models.CharField(max_length=5)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("database", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OrgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("email", models.CharField(max_length=50, null=True, unique=True)),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgPrefectBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocktype", models.CharField(max_length=25)),
                ("blockid", models.CharField(max_length=36, unique=True)),
                ("blockname", models.CharField(max_length=100, unique=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="org",
            name="dbt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ddpui.orgdbt",
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invited_email", models.CharField(max_length=50)),
                ("invited_on", models.DateTimeField()),
                ("invite_code", models.CharField(max_length=36)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
            ],
        ),
    ]
