# Generated by Django 4.1.7 on 2023-04-05 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ddpui", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuser",
            name="active",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="orguser",
            name="active",
        ),
        migrations.RemoveField(
            model_name="orguser",
            name="email",
        ),
        migrations.AddField(
            model_name="adminuser",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orguser",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
