# Generated by Django 4.1.7 on 2023-04-07 13:19

import ddpui.models.org_user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0002_remove_adminuser_active_remove_adminuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orguser",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "REPORT_VIEWER"),
                    (2, "PIPELINE_MANAGER"),
                    (3, "ACCOUNT_MANAGER"),
                ],
                default=ddpui.models.org_user.OrgUserRole["REPORT_VIEWER"],
            ),
        ),
    ]
