# Generated by Django 4.1.7 on 2023-04-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0004_invitation_invited_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgdbt",
            name="database",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="host",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="password",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="port",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="username",
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="credentials",
            field=models.TextField(null=True),
        ),
    ]
