# Generated by Django 4.1.7 on 2023-04-17 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0005_orgprefectblock_displayname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgdbt",
            old_name="dbtversion",
            new_name="dbt_version",
        ),
        migrations.RenameField(
            model_name="orgdbt",
            old_name="targetname",
            new_name="target_name",
        ),
        migrations.RenameField(
            model_name="orgdbt",
            old_name="targetschema",
            new_name="target_schema",
        ),
        migrations.RenameField(
            model_name="orgdbt",
            old_name="targettype",
            new_name="target_type",
        ),
        migrations.RenameField(
            model_name="orgprefectblock",
            old_name="blockid",
            new_name="block_id",
        ),
        migrations.RenameField(
            model_name="orgprefectblock",
            old_name="blockname",
            new_name="block_name",
        ),
        migrations.RenameField(
            model_name="orgprefectblock",
            old_name="blocktype",
            new_name="block_type",
        ),
        migrations.RenameField(
            model_name="orgprefectblock",
            old_name="displayname",
            new_name="display_name",
        ),
    ]
