# Generated by Django 4.1.7 on 2023-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0007_orgdbt_gitrepo_access_token_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgprefectblock",
            name="seq",
            field=models.SmallIntegerField(null=True),
        ),
    ]
