# Generated by Django 4.1.7 on 2023-04-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0008_orgprefectblock_seq"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wtype", models.CharField(max_length=25)),
                ("credentials", models.CharField(max_length=200)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"
                    ),
                ),
            ],
        ),
    ]
