# Generated by Django 4.1.7 on 2023-04-18 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0009_remove_orgdbt_database_remove_orgdbt_host_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgdbt",
            name="database",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="host",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="password",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="port",
        ),
        migrations.RemoveField(
            model_name="orgdbt",
            name="username",
        ),
    ]
