# Generated by Django 4.1.7 on 2023-04-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0011_orgflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="dbt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orgdbt",
            ),
        ),
    ]
