# Generated by Django 4.1.7 on 2023-05-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0013_orgwarehouse_airbyte_destination_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgdbt",
            name="target_schema",
            field=models.CharField(max_length=50),
        ),
    ]
