# Generated by Django 4.1.7 on 2023-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0014_alter_orgdbt_target_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgwarehouse",
            name="airbyte_norm_op_id",
            field=models.TextField(max_length=36, null=True),
        ),
    ]
