# Generated by Django 4.1.7 on 2023-05-18 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0015_orgwarehouse_airbyte_norm_op_id"),
        ("ddpui", "0015_rename_target_schema_orgdbt_default_schema_and_more"),
    ]

    operations = []
