# Generated by Django 4.1.7 on 2023-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0016_merge_20230518_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgdataflow",
            name="cron",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
