# Generated by Django 4.1.7 on 2023-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0019_remove_orgdataflow_flow_id_orgdataflow_connection_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgprefectblock",
            name="command",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orgprefectblock",
            name="dbt_target_schema",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
