# Generated by Django 4.1.7 on 2023-07-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0021_orguser_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="airbyte_workspace_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="org",
            name="slug",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="orgdataflow",
            name="connection_id",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="orgdataflow",
            name="cron",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="orgdataflow",
            name="deployment_id",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="orgdataflow",
            name="deployment_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgprefectblock",
            name="command",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgprefectblock",
            name="dbt_target_schema",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orgprefectblock",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgprefectblock",
            name="seq",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orgwarehouse",
            name="airbyte_destination_id",
            field=models.TextField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="orgwarehouse",
            name="airbyte_norm_op_id",
            field=models.TextField(blank=True, max_length=36, null=True),
        ),
    ]
