# Generated by Django 4.1.7 on 2023-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0021_orguser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="viz_login_type",
            field=models.CharField(
                choices=[("basic", "BASIC_AUTH"), ("google", "GOOGLE_AUTH")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="viz_url",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
