# Generated by Django 4.1.7 on 2023-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0021_orguser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[("pending", "PENDING"), ("accepted", "ACCEPTED")],
                default="pending",
                max_length=50,
            ),
        ),
    ]
