# Generated by Django 4.1.7 on 2023-08-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0022_invitation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invited_org",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"
            ),
        ),
    ]
