# Generated by Django 4.1.7 on 2023-08-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0022_org_viz_login_type_org_viz_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgdbt",
            name="dbt_version",
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="dbt_venv",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
