# Generated by Django 4.1.7 on 2023-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0024_userattributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgwarehouse",
            name="name",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
    ]
