# Generated by Django 4.1.7 on 2023-09-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0025_orgwarehouse_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flow_run_id",
                    models.TextField(blank=True, default="", max_length=36),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.orgprefectblock",
                        unique=True,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
            ],
        ),
    ]
