# Generated by Django 4.1.7 on 2023-09-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0026_blocklock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocklock",
            name="block",
        ),
        migrations.AddField(
            model_name="blocklock",
            name="opb",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ddpui.orgprefectblock",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DataflowBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.orgdataflow",
                    ),
                ),
                (
                    "opb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.orgprefectblock",
                    ),
                ),
            ],
        ),
    ]
