# Generated by Django 4.1.7 on 2023-11-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0027_remove_blocklock_block_blocklock_opb_dataflowblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgwarehouse",
            name="superset_creds",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
