# Generated by Django 4.1.7 on 2023-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0029_prefectflowrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdataflow",
            name="dataflow_type",
            field=models.CharField(
                choices=[("orchestrate", "orchestrate"), ("manual", "manual")],
                default="orchestrate",
                max_length=25,
            ),
        ),
    ]
