# Generated by Django 4.1.7 on 2023-12-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0032_orgprefectblockv1"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgDataFlowv1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("deployment_name", models.CharField(max_length=100, null=True)),
                (
                    "deployment_id",
                    models.CharField(max_length=36, null=True, unique=True),
                ),
                ("cron", models.CharField(max_length=36, null=True)),
                (
                    "dataflow_type",
                    models.CharField(
                        choices=[("orchestrate", "orchestrate"), ("manual", "manual")],
                        default="orchestrate",
                        max_length=25,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"
                    ),
                ),
            ],
        ),
    ]
