# Generated by Django 4.1.7 on 2023-12-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0033_orgdataflowv1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafloworgtask",
            name="dataflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ddpui.orgdataflowv1"
            ),
        ),
    ]
