# Generated by Django 4.1.7 on 2023-12-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0034_alter_datafloworgtask_dataflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_run_id",
                    models.TextField(blank=True, default="", max_length=36),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
                (
                    "orgtask",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orgtask"
                    ),
                ),
            ],
        ),
    ]
