# Generated by Django 4.1.7 on 2023-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0034_alter_datafloworgtask_dataflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="can_accept_tnc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orguser",
            name="can_accept_tnc",
            field=models.BooleanField(default=False),
        ),
    ]
