# Generated by Django 4.1.7 on 2024-01-09 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0038_org_is_demo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgwarehouse",
            name="superset_creds",
        ),
    ]
