# Generated by Django 4.1.7 on 2024-01-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0039_remove_orgwarehouse_superset_creds"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklock",
            name="locking_dataflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ddpui.orgdataflowv1",
            ),
        ),
    ]
