# Generated by Django 4.1.7 on 2024-02-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0041_orgtask_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgtask",
            name="generated_by",
            field=models.CharField(
                choices=[("system", "SYSTEM"), ("client", "CLIENT")],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_system",
            field=models.BooleanField(default=True),
        ),
    ]
