# Generated by Django 4.1.7 on 2024-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0042_orgtask_generated_by_task_is_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgdbt",
            name="gitrepo_url",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
