# Generated by Django 4.1.7 on 2024-02-12 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0043_alter_orgdbt_gitrepo_url"),
        ("ddpui", "0043_orgwarehouse_bq_location"),
    ]

    operations = []
