# Generated by Django 4.1.7 on 2024-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0046_orgdbtmodel_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="userattributes",
            name="is_platform_admin",
            field=models.BooleanField(default=False),
        ),
    ]
