# Generated by Django 4.1.7 on 2024-02-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0047_userattributes_is_platform_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafloworgtask",
            name="seq",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="orgtask",
            name="uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
