# Generated by Django 4.1.7 on 2024-02-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0048_datafloworgtask_seq_orgtask_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbtEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config", models.JSONField(null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="ddpui.orgdbtmodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="ddpui.orgdbtmodel",
                    ),
                ),
            ],
        ),
    ]
