# Generated by Django 4.1.7 on 2024-02-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0050_remove_orgdbtmodel_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbtmodel",
            name="type",
            field=models.CharField(
                choices=[("source", "SOURCE"), ("model", "MODEL")],
                default="model",
                max_length=50,
            ),
        ),
    ]
