# Generated by Django 4.1.7 on 2024-02-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0052_orgdbtmodel_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtedge",
            name="config",
        ),
        migrations.RemoveField(
            model_name="dbtedge",
            name="source",
        ),
        migrations.RemoveField(
            model_name="dbtedge",
            name="target",
        ),
        migrations.AddField(
            model_name="dbtedge",
            name="from_node",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_node",
                to="ddpui.orgdbtmodel",
            ),
        ),
        migrations.AddField(
            model_name="dbtedge",
            name="to_node",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_node",
                to="ddpui.orgdbtmodel",
            ),
        ),
        migrations.AddField(
            model_name="orgdbtmodel",
            name="config",
            field=models.JSONField(null=True),
        ),
    ]
