# Generated by Django 4.1.7 on 2024-02-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0052_orgdbtmodel_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="transform_type",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
