# Generated by Django 4.1.7 on 2024-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0052_orgdbtmodel_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgwarehouse",
            name="airbyte_docker_image_tag",
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="orgwarehouse",
            name="airbyte_docker_repository",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
