# Generated by Django 4.1.7 on 2024-02-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0053_remove_dbtedge_config_remove_dbtedge_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbtmodel",
            name="source_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
