# Generated by Django 4.1.7 on 2024-02-28 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0053_orgwarehouse_airbyte_docker_image_tag_and_more"),
        ("ddpui", "0054_orgdbtmodel_source_name"),
    ]

    operations = []
