# Generated by Django 4.1.7 on 2024-02-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0055_merge_20240228_1312"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgdbtmodel",
            name="config",
        ),
        migrations.AddField(
            model_name="orgdbtmodel",
            name="output_cols",
            field=models.JSONField(default=list),
        ),
    ]
