# Generated by Django 4.1.7 on 2024-03-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0055_merge_20240228_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="transform_type",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
