# Generated by Django 4.1.7 on 2024-02-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0057_orgdbtoperation"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbtmodel",
            name="under_construction",
            field=models.BooleanField(default=False),
        ),
    ]
