# Generated by Django 4.1.7 on 2024-02-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0058_orgdbtmodel_under_construction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgdbtmodel",
            name="display_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgdbtmodel",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
