# Generated by Django 4.1.7 on 2024-03-02 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0056_orgdbt_transform_type"),
        ("ddpui", "0059_alter_orgdbtmodel_display_name_and_more"),
    ]

    operations = []
