# Generated by Django 4.1.7 on 2024-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0060_merge_20240302_1014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgdbtmodel",
            name="display_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="orgdbtmodel",
            name="name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="orgdbtmodel",
            name="sql_path",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
