# Generated by Django 4.1.7 on 2024-04-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0065_role_level_alter_permission_uuid_alter_role_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invited_new_role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ddpui.role"
            ),
        ),
    ]
