# Generated by Django 4.1.7 on 2024-04-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0066_invitation_invited_new_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("lock_id", models.UUIDField(editable=False, null=True, unique=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
            ],
        ),
    ]
