# Generated by Django 4.1.7 on 2024-04-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0066_invitation_invited_new_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgwarehouse",
            name="credentials",
            field=models.CharField(max_length=1000),
        ),
    ]
