# Generated by Django 4.1.7 on 2024-04-22 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0067_alter_orgwarehouse_credentials"),
        ("ddpui", "0067_canvaslock"),
    ]

    operations = []
