# Generated by Django 4.1.7 on 2024-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0068_merge_20240422_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklock",
            name="celery_task_id",
            field=models.TextField(max_length=36, null=True),
        ),
    ]
