# Generated by Django 4.1.7 on 2024-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0069_tasklock_celery_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="ses_whitelisted_email",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
