# Generated by Django 4.1.7 on 2024-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0070_org_ses_whitelisted_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgtask",
            name="connection_id",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
