# Generated by Django 4.1.7 on 2024-05-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0071_alter_orgtask_connection_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdataflowv1",
            name="reset_conn_dataflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orgdataflowv1",
            ),
        ),
    ]
