# Generated by Django 4.1.7 on 2024-05-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0072_orgdataflowv1_reset_conn_dataflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSchemaChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "connection_id",
                    models.CharField(max_length=36, null=True, unique=True),
                ),
                ("schema_change", models.CharField(max_length=36, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"
                    ),
                ),
            ],
        ),
    ]
