# Generated by Django 4.1.7 on 2024-05-23 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0072_orgdataflowv1_reset_conn_dataflow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataflowblock",
            name="dataflow",
        ),
        migrations.RemoveField(
            model_name="dataflowblock",
            name="opb",
        ),
        migrations.RemoveField(
            model_name="orgdataflow",
            name="org",
        ),
        migrations.DeleteModel(
            name="BlockLock",
        ),
        migrations.DeleteModel(
            name="DataflowBlock",
        ),
        migrations.DeleteModel(
            name="OrgDataFlow",
        ),
    ]
