# Generated by Django 4.1.7 on 2024-05-22 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0073_orgschemachange"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgschemachange",
            old_name="schema_change",
            new_name="change_type",
        ),
    ]
