# Generated by Django 4.1.7 on 2024-05-22 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0074_rename_schema_change_orgschemachange_change_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgschemachange",
            name="name",
        ),
    ]
