# Generated by Django 4.1.7 on 2024-05-26 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0073_remove_dataflowblock_dataflow_and_more"),
        ("ddpui", "0075_remove_orgschemachange_name"),
    ]

    operations = []
