# Generated by Django 5.0.6 on 2024-05-27 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0076_merge_20240526_2356"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrgPrefectBlock",
        ),
    ]
