# Generated by Django 4.2 on 2024-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0077_delete_orgprefectblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="use_elementary",
            field=models.BooleanField(default=False),
        ),
    ]
