# Generated by Django 4.2 on 2024-06-23 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0077_delete_orgprefectblock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgwarehouse",
            name="airbyte_norm_op_id",
        ),
    ]
