# Generated by Django 4.2 on 2024-06-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0078_remove_orgwarehouse_airbyte_norm_op_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdataflowv1",
            name="generated_by",
            field=models.CharField(
                choices=[("system", "SYSTEM"), ("client", "CLIENT")],
                default="client",
                max_length=50,
            ),
        ),
    ]
