# Generated by Django 4.2 on 2024-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0078_remove_orgwarehouse_airbyte_norm_op_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("log_summarization", "LOG_SUMMARIZATION"),
                            ("long_text_summarization", "LONG_TEXT_SUMMARIZATION"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
