# Generated by Django 4.2 on 2024-06-27 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0079_assistantprompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("flow_run_id", models.TextField(null=True)),
                ("assistant_prompt", models.TextField(null=True)),
                ("user_prompts", models.JSONField(default=list, null=True)),
                ("session_id", models.CharField(max_length=200, null=True)),
                ("response", models.JSONField()),
                ("response_meta", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"
                    ),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.orguser",
                    ),
                ),
            ],
        ),
    ]
