# Generated by Django 4.2 on 2024-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0080_llmsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="airbyte_job_id",
            field=models.IntegerField(null=True),
        ),
    ]
