# Generated by Django 4.2 on 2024-07-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0081_llmsession_airbyte_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="task_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="llmsession",
            name="flow_run_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="llmsession",
            name="response",
            field=models.JSONField(null=True),
        ),
    ]
