# Generated by Django 4.2 on 2024-07-03 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0082_llmsession_task_id_alter_llmsession_flow_run_id_and_more"),
        ("ddpui", "0082_notification_userpreferences_notificationrecipient"),
    ]

    operations = []
