# Generated by Django 4.2 on 2024-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0083_merge_20240703_1732"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="session_status",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
