# Generated by Django 4.2 on 2024-07-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0084_llmsession_session_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="session_name",
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
