# Generated by Django 4.2 on 2024-07-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0084_llmsession_session_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_id", models.CharField(max_length=36)),
                ("attempt", models.IntegerField(default=0)),
                ("status", models.TextField()),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("manual", "manual"), ("orchestrate", "orchestrate")]
                    ),
                ),
                ("sync_time", models.DateTimeField()),
                ("sync_duration_s", models.IntegerField(default=0)),
                ("sync_records", models.IntegerField(default=0)),
                ("sync_data_volume_b", models.IntegerField(default=0)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
        ),
    ]
