# Generated by Django 4.2 on 2024-07-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0087_alter_datafloworgtask_dataflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgdbtoperation",
            name="dbtmodel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="ddpui.orgdbtmodel",
            ),
        ),
    ]
