# Generated by Django 4.2 on 2024-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0088_alter_orgdbtoperation_dbtmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefectflowrun",
            name="deployment_id",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
