# Generated by Django 4.2 on 2024-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0089_alter_prefectflowrun_deployment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncstats",
            name="job_id",
            field=models.IntegerField(null=True),
        ),
    ]
