# Generated by Django 4.2 on 2024-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0090_syncstats_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefectflowrun",
            name="retries",
            field=models.SmallIntegerField(default=0),
        ),
    ]
