# Generated by Django 4.2 on 2024-08-30 05:36

import ddpui.models.org
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0092_assistantprompt_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="is_demo",
        ),
        migrations.AddField(
            model_name="org",
            name="type",
            field=models.CharField(
                choices=[("demo", "DEMO"), ("trial", "TRIAL"), ("subscription", "SUBSCRIPTION")],
                default=ddpui.models.org.OrgType["SUBSCRIPTION"],
                max_length=50,
            ),
        ),
    ]
