# Generated by Django 4.2 on 2024-09-03 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0085_llmsession_session_name"),
        ("ddpui", "0093_remove_org_is_demo_org_type"),
    ]

    operations = []
