# Generated by Django 4.2 on 2024-09-03 12:49

import ddpui.models.llm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0095_alter_llmsession_session_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="request_meta",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="llmsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("log_summarization", "LOG_SUMMARIZATION"),
                    ("long_text_summarization", "LONG_TEXT_SUMMARIZATION"),
                ],
                default=ddpui.models.llm.LlmAssistantType["LOG_SUMMARIZATION"],
                max_length=100,
            ),
        ),
    ]
