# Generated by Django 4.2 on 2024-09-04 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0097_userprompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistantprompt",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="assistantprompt",
            name="updated_at",
        ),
    ]
