# Generated by Django 4.2 on 2024-09-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0098_remove_assistantprompt_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprompt",
            name="label",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
