# Generated by Django 4.2 on 2024-09-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0099_userprompt_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="feedback",
            field=models.TextField(null=True),
        ),
    ]
