# Generated by Django 4.2 on 2024-09-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0100_llmsession_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_by",
                to="ddpui.orguser",
            ),
        ),
    ]
