# Generated by Django 4.2 on 2024-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0101_llmsession_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="orguser",
            name="llm_optin",
            field=models.BooleanField(default=False),
        ),
    ]
