# Generated by Django 4.2 on 2024-09-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0101_connectionjob_connectionmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgschemachange",
            name="schedule_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.connectionjob",
            ),
        ),
    ]
