# Generated by Django 4.2 on 2024-11-06 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0103_connectionjob_connectionmeta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="discord_webhook",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="enable_discord_notifications",
        ),
    ]
