# Generated by Django 4.2 on 2024-11-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0105_orgpreferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgpreferences",
            name="llm_optin_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvedby",
                to="ddpui.orguser",
            ),
        ),
    ]
