# Generated by Django 4.2 on 2024-11-12 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0106_alter_orgpreferences_llm_optin_approved_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSupersets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("container_name", models.CharField(blank=True, max_length=255, null=True)),
                ("superset_version", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orgInfo",
                        to="ddpui.org",
                    ),
                ),
            ],
        ),
    ]
