# Generated by Django 4.2 on 2024-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0107_orgsupersets"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="llm_optin",
            field=models.BooleanField(default=False),
        ),
    ]
