# Generated by Django 4.2 on 2024-11-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0108_userpreferences_llm_optin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgpreferences",
            name="org",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to="ddpui.org",
            ),
        ),
        migrations.AlterField(
            model_name="orgsupersets",
            name="org",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="orgInfo", to="ddpui.org"
            ),
        ),
    ]
