# Generated by Django 4.2 on 2024-11-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0109_alter_orgpreferences_org_alter_orgsupersets_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="discord_webhook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="enable_discord_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
