# Generated by Django 4.2 on 2024-11-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0112_rename_llm_optin_userpreferences_disclaimer_shown"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgplans",
            name="upgrade_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="enable_llm_request",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="enable_llm_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_request",
                to="ddpui.orguser",
            ),
        ),
    ]
