# Generated by Django 4.2 on 2024-11-24 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0104_orgdataflowv1_clear_conn_dataflow"),
        ("ddpui", "0113_orgplans_upgrade_requested_and_more"),
    ]

    operations = []
