# Generated by Django 4.2 on 2024-11-27 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0114_merge_20241124_1514"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="type",
        ),
    ]
