# Generated by Django 4.2 on 2025-02-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0115_remove_org_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_subject",
            field=models.TextField(default="Message from Dalgo"),
            preserve_default=False,
        ),
    ]
