# Generated by Django 4.2 on 2025-02-25 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0116_notification_email_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="pgvector_creds",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="OrgWarehouseRagTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("training_sql", models.TextField(null=True)),
                ("exclude", models.JSONField(null=True)),
                ("last_trained_at", models.DateTimeField(null=True)),
                ("last_log", models.JSONField(null=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orgwarehouse"
                    ),
                ),
            ],
        ),
    ]
