# Generated by Django 4.2 on 2025-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0116_notification_email_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdataflowv1",
            name="meta",
            field=models.JSONField(null=True),
        ),
    ]
