# Generated by Django 4.2 on 2025-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0117_org_pgvector_creds_orgwarehouseragtraining"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsession",
            name="version",
            field=models.CharField(choices=[("v0", "v0"), ("v1", "v1")], default="v0", null=True),
        ),
    ]
