# Generated by Django 4.2 on 2025-03-08 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0117_orgwren"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
