# Generated by Django 4.2 on 2025-04-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0117_orgwren"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdataflowv1",
            name="meta",
            field=models.JSONField(null=True),
        ),
    ]
