# Generated by Django 4.2 on 2025-03-04 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0117_orgwren"),
        ("ddpui", "0118_llmsession_version"),
    ]

    operations = []
