# Generated by Django 4.2 on 2025-05-06 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0118_orgdataflowv1_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectionmeta",
            name="schedule_large_jobs",
        ),
    ]
