# Generated by Django 4.2 on 2025-05-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0118_orgdataflowv1_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefectflowrun",
            name="orguser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orguser",
            ),
        ),
    ]
