# Generated by Django 4.2 on 2025-04-08 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0118_orgdataflowv1_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgDbtModelv1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("uuid", models.UUIDField(editable=False, unique=True)),
                ("name", models.CharField(max_length=300, null=True)),
                ("display_name", models.CharField(max_length=300, null=True)),
                ("schema", models.CharField(max_length=300, null=True)),
                ("sql_path", models.CharField(max_length=300, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("source", "SOURCE"), ("model", "MODEL")], max_length=50
                    ),
                ),
                ("source_name", models.CharField(max_length=300, null=True)),
                ("output_cols", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrgDbtOperationv1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("uuid", models.UUIDField(editable=False, unique=True)),
                ("op_type", models.CharField(max_length=100)),
                ("output_cols", models.JSONField(default=list)),
                ("config", models.JSONField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DbtNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(editable=False, unique=True)),
                (
                    "dbtmodel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model",
                        to="ddpui.orgdbtmodelv1",
                    ),
                ),
                (
                    "dbtoperation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation",
                        to="ddpui.orgdbtoperationv1",
                    ),
                ),
                (
                    "orgdbt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orgdbt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DbtEdgev1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("uuid", models.UUIDField(editable=False, unique=True)),
                ("config", models.JSONField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_node",
                        to="ddpui.dbtnode",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_node",
                        to="ddpui.dbtnode",
                    ),
                ),
            ],
        ),
    ]
