# Generated by Django 4.2 on 2025-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0119_prefectflowrun_orguser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefectflowrun",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
