# Generated by Django 4.2 on 2025-05-13 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0119_remove_connectionmeta_schedule_large_jobs"),
        ("ddpui", "0120_alter_prefectflowrun_start_time"),
    ]

    operations = []
