# Generated by Django 4.2 on 2025-06-03 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0122_set_uuid_in_orgtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgtask",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
