# Generated by Django 4.2 on 2025-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0123_alter_orgtask_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionmeta",
            name="connection_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
