# Generated by Django 4.2 on 2025-07-01 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0124_connectionmeta_connection_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="invited_role",
        ),
        migrations.RemoveField(
            model_name="orguser",
            name="role",
        ),
    ]
