# Generated by Django 4.2 on 2025-06-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0124_connectionmeta_connection_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="dalgouser_superset_creds_key",
            field=models.TextField(null=True),
        ),
    ]
