# Generated by Django 4.2 on 2025-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0124_connectionmeta_connection_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirbyteJob",
            fields=[
                ("job_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("job_type", models.CharField(max_length=20)),
                ("config_id", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("reset_config", models.JSONField(null=True)),
                ("refresh_config", models.JSONField(null=True)),
                ("stream_stats", models.JSONField(null=True)),
                ("records_emitted", models.BigIntegerField(default=0)),
                ("bytes_emitted", models.BigIntegerField(default=0)),
                ("records_committed", models.BigIntegerField(default=0)),
                ("bytes_committed", models.BigIntegerField(default=0)),
                ("attempts", models.JSONField(null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
