# Generated by Django 4.2 on 2025-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0125_remove_invitation_invited_role_remove_orguser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("incident", "Incident"),
                    ("schema_change", "Schema Change"),
                    ("job_failure", "Job Failure"),
                    ("late_runs", "Late Runs"),
                    ("dbt_test_failure", "DBT Test Failure"),
                ],
                default="incident",
                help_text="Category of the notification",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="dismissed_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have dismissed this urgent notification",
                related_name="dismissed_notifications",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="subscribe_dbt_test_failure_notifications",
            field=models.BooleanField(
                default=True, help_text="Subscribe to DBT test failure notifications"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="subscribe_incident_notifications",
            field=models.BooleanField(
                default=True, help_text="Subscribe to incident notifications"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="subscribe_job_failure_notifications",
            field=models.BooleanField(
                default=True, help_text="Subscribe to job failure notifications"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="subscribe_late_runs_notifications",
            field=models.BooleanField(
                default=True, help_text="Subscribe to late runs notifications"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="subscribe_schema_change_notifications",
            field=models.BooleanField(
                default=True, help_text="Subscribe to schema change notifications"
            ),
        ),
    ]
