# Generated by Django 4.2 on 2025-07-03 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0125_airbytejob"),
        ("ddpui", "0125_remove_invitation_invited_role_remove_orguser_role"),
    ]

    operations = []
