# Generated by Django 4.2 on 2025-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_notification_category_notification_dismissed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="dismissed_by",
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incident", "Incident"),
                    ("schema_change", "Schema Change"),
                    ("job_failure", "Job Failure"),
                    ("late_runs", "Late Runs"),
                    ("dbt_test_failure", "DBT Test Failure"),
                ],
                default=None,
                help_text="Category of the notification",
                max_length=20,
                null=True,
            ),
        ),
    ]
