# Generated by Django 4.2 on 2025-07-31 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_merge_20250703_0642"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="dalgouser_superset_creds_key",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("line", "Line Chart"),
                            ("number", "Number Chart"),
                            ("map", "Map Chart"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "computation_type",
                    models.CharField(
                        choices=[("raw", "Raw Data"), ("aggregated", "Aggregated Data")],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                (
                    "extra_config",
                    models.JSONField(
                        default=dict, help_text="Create chart form config including customizations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        db_column="last_modified_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_modified_by",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
        ),
    ]
