# Generated by Django 4.2 on 2025-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_merge_20250703_0642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgwarehouse",
            name="name",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
