# Generated by Django 4.2 on 2025-06-27 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_chart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                ("schema", models.CharField(max_length=256)),
                ("table", models.CharField(max_length=256)),
                ("temporal_column", models.CharField(max_length=256, null=True)),
                ("dimension_columns", models.JSONField(default=list)),
                (
                    "aggregation_function",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("count_distinct", "Count Distinct"),
                            ("sum", "Sum"),
                            ("min", "Min"),
                            ("max", "Max"),
                            ("average", "Average"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("aggregation_column", models.CharField(max_length=256, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chart",
            name="metric",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddpui.metric"
            ),
        ),
    ]
