# Generated by Django 4.2 on 2025-07-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_merge_20250703_0642"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("line", "Line Chart"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "computation_type",
                    models.CharField(
                        choices=[("raw", "Raw Data"), ("aggregated", "Aggregated Data")],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Chart configuration including columns and customizations",
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="ddpui.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="ddpui.orguser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChartSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("data", models.JSONField(help_text="Cached chart data")),
                ("echarts_config", models.JSONField(help_text="Generated ECharts configuration")),
                (
                    "query_hash",
                    models.CharField(
                        help_text="Hash of the query for cache invalidation", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="When this snapshot expires")),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="ddpui.chart",
                    ),
                ),
            ],
        ),
    ]
