# Generated by Django 4.2 on 2025-07-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_merge_20250703_0642"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("line", "Line Chart"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "computation_type",
                    models.CharField(
                        choices=[("raw", "Raw Data"), ("aggregated", "Aggregated Data")],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Chart configuration including columns and customizations",
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="ddpui.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "charts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChartSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("data", models.JSONField(help_text="Cached chart data")),
                ("echarts_config", models.JSONField(help_text="Generated ECharts configuration")),
                (
                    "query_hash",
                    models.CharField(
                        help_text="Hash of the query for cache invalidation", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="When this snapshot expires")),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="ddpui.chart",
                    ),
                ),
            ],
            options={
                "db_table": "chart_snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chartsnapshot",
            index=models.Index(
                fields=["chart", "created_at"], name="chart_snaps_chart_i_7d50f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartsnapshot",
            index=models.Index(fields=["query_hash"], name="chart_snaps_query_h_b8d21a_idx"),
        ),
        migrations.AddIndex(
            model_name="chartsnapshot",
            index=models.Index(fields=["expires_at"], name="chart_snaps_expires_a10b6b_idx"),
        ),
        migrations.AddIndex(
            model_name="chart",
            index=models.Index(fields=["org", "user"], name="charts_org_id_270048_idx"),
        ),
        migrations.AddIndex(
            model_name="chart",
            index=models.Index(fields=["chart_type"], name="charts_chart_t_dde08c_idx"),
        ),
        migrations.AddIndex(
            model_name="chart",
            index=models.Index(fields=["created_at"], name="charts_created_f0ac6f_idx"),
        ),
    ]
