# Generated by Django 4.2 on 2025-08-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0127_alter_orgwarehouse_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionmeta",
            name="description",
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text="Description of the connection (max 100 characters)",
                null=True,
            ),
        ),
    ]
