# Generated by Django 4.2 on 2025-08-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0127_org_dalgouser_superset_creds_key_chart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[("native", "NATIVE"), ("superset", "SUPERSET")],
                        default="native",
                        max_length=20,
                    ),
                ),
                ("grid_columns", models.IntegerField(default=12)),
                (
                    "layout_config",
                    models.JSONField(default=dict, help_text="Grid layout positions and sizes"),
                ),
                (
                    "components",
                    models.JSONField(default=dict, help_text="Dashboard components configuration"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        db_column="last_modified_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards_modified",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "db_table": "dashboard",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("lock_token", models.CharField(max_length=36, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock",
                        to="ddpui.dashboard",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_lock",
            },
        ),
        migrations.CreateModel(
            name="DashboardFilter",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("value", "VALUE"), ("numerical", "NUMERICAL")], max_length=20
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("column_name", models.CharField(max_length=255)),
                ("settings", models.JSONField(default=dict, help_text="Filter-specific settings")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="ddpui.dashboard",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_filter",
                "ordering": ["order"],
            },
        ),
    ]
