# Generated by Django 4.2 on 2025-08-18 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_notification_category_and_more"),
        ("ddpui", "0127_alter_orgwarehouse_name"),
    ]

    operations = []
