# Generated by Django 4.2 on 2025-07-16 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0126_merge_20250703_0642"),
        ("ddpui", "0127_chart_metadata_metric_chart_metric"),
    ]

    operations = []
