# Generated by Django 4.2 on 2025-07-16 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0127_chart_chartsnapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chart",
            new_name="charts_org_id_159c39_idx",
            old_name="charts_org_id_10f8b4_idx",
        ),
        migrations.RenameIndex(
            model_name="chart",
            new_name="charts_schema__e1f776_idx",
            old_name="charts_schema_name_9f8b4e_idx",
        ),
        migrations.RenameIndex(
            model_name="chart",
            new_name="charts_chart_t_dde08c_idx",
            old_name="charts_chart_type_7f8b4d_idx",
        ),
        migrations.RenameIndex(
            model_name="chartsnapshot",
            new_name="chart_snaps_chart_i_bfd72d_idx",
            old_name="chart_snapshots_chart_id_8f8b4c_idx",
        ),
        migrations.RenameIndex(
            model_name="chartsnapshot",
            new_name="chart_snaps_expires_a10b6b_idx",
            old_name="chart_snapshots_expires_at_6f8b4b_idx",
        ),
    ]
