# Generated by Django 4.2 on 2025-07-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0128_rename_charts_org_id_10f8b4_idx_charts_org_id_159c39_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsnapshot",
            name="chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="ddpui.chart",
            ),
        ),
    ]
