# Generated by Django 4.2 on 2025-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0128_dashboard_dashboardlock_dashboardfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardfilter",
            name="name",
            field=models.CharField(
                default="", help_text="Display name for the filter", max_length=255
            ),
        ),
    ]
