# Generated by Django 4.2 on 2025-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0129_add_filter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardfilter",
            name="filter_type",
            field=models.CharField(
                choices=[("value", "VALUE"), ("numerical", "NUMERICAL"), ("datetime", "DATETIME")],
                max_length=20,
            ),
        ),
    ]
