# Generated by Django 4.2 on 2025-08-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0130_add_datetime_filter_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=10)),
                ("region_code", models.CharField(max_length=10)),
                ("display_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ddpui.georegion",
                    ),
                ),
            ],
            options={
                "db_table": "ddpui_georegion",
            },
        ),
        migrations.CreateModel(
            name="GeoJSON",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("geojson_data", models.JSONField()),
                ("properties_key", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        db_column="org_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geojsons",
                        to="ddpui.org",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        db_column="region_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geojsons",
                        to="ddpui.georegion",
                    ),
                ),
            ],
            options={
                "db_table": "ddpui_geojson",
            },
        ),
        migrations.AddIndex(
            model_name="georegion",
            index=models.Index(
                fields=["country_code", "type"], name="ddpui_geore_country_1fabb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="georegion",
            index=models.Index(fields=["parent_id"], name="ddpui_geore_parent__fe2196_idx"),
        ),
        migrations.AddIndex(
            model_name="geojson",
            index=models.Index(
                fields=["region_id", "org_id"], name="ddpui_geojs_region__c13959_idx"
            ),
        ),
    ]
