# Generated by Django 4.2 on 2025-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0130_add_datetime_filter_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="target_screen_size",
            field=models.CharField(
                choices=[
                    ("desktop", "Desktop"),
                    ("tablet", "Tablet"),
                    ("mobile", "Mobile"),
                    ("a4", "A4"),
                ],
                default="desktop",
                help_text="Target screen size for dashboard design",
                max_length=20,
            ),
        ),
    ]
