# Generated by Django 4.2 on 2025-08-17 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0127_alter_orgwarehouse_name"),
        ("ddpui", "0132_dashboard_target_screen_size"),
    ]

    operations = []
