# Generated by Django 4.2 on 2025-08-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0133_merge_20250817_0743"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="filter_layout",
            field=models.CharField(
                choices=[("vertical", "Vertical"), ("horizontal", "Horizontal")],
                default="vertical",
                help_text="Layout for dashboard filters - vertical sidebar or horizontal top bar",
                max_length=20,
            ),
        ),
    ]
