# Generated by Django 4.2 on 2025-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0134_dashboard_filter_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="If True, dashboard is accessible via public URL"
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="last_public_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="public_access_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="public_disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="public_share_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique token for public sharing URLs",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="public_shared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
