# Generated by Django 4.2 on 2025-08-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0135_add_dashboard_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="is_org_default",
            field=models.BooleanField(
                default=False,
                help_text="If True, this dashboard is the organization's default landing page",
            ),
        ),
        migrations.AddField(
            model_name="orguser",
            name="landing_dashboard",
            field=models.ForeignKey(
                blank=True,
                help_text="User's personal landing dashboard",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_with_as_landing",
                to="ddpui.dashboard",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_org_default", True)),
                fields=("org",),
                name="unique_org_default_dashboard",
            ),
        ),
    ]
