# Generated by Django 4.2 on 2025-10-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0137_update_landing_page_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("flag_name", models.CharField(max_length=100)),
                ("flag_value", models.BooleanField()),
                (
                    "org",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"
                    ),
                ),
            ],
        ),
    ]
