# Generated by Django 4.2 on 2025-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0138_orgfeatureflag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orgfeatureflag",
            unique_together={("org", "flag_name")},
        ),
        migrations.AddIndex(
            model_name="orgfeatureflag",
            index=models.Index(fields=["org", "flag_name"], name="ddpui_orgfe_org_id_db0a87_idx"),
        ),
        migrations.AddIndex(
            model_name="orgfeatureflag",
            index=models.Index(
                condition=models.Q(("org__isnull", True)),
                fields=["flag_name"],
                name="unique_global_flag",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgfeatureflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org__isnull", True)),
                fields=("flag_name",),
                name="unique_global_feature_flag",
            ),
        ),
    ]
