# Generated by Django 4.2 on 2025-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0139_add_orgfeatureflag_uniqueness_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="website",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
