# Generated by Django 4.2 on 2025-10-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0140_org_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="orguser",
            name="work_domain",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
