# Generated by Django 4.2 on 2025-11-10 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0141_orguser_work_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("source", "SOURCE"),
                            ("model", "MODEL"),
                            ("operation", "OPERATION"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("operation_config", models.JSONField(default=dict)),
                ("output_cols", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dbtmodel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.orgdbtmodel",
                    ),
                ),
                (
                    "orgdbt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orgdbt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CanvasEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seq", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_node",
                        to="ddpui.canvasnode",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_node",
                        to="ddpui.canvasnode",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="canvasedge",
            index=models.Index(fields=["from_node"], name="ddpui_canva_from_no_28ad3a_idx"),
        ),
        migrations.AddIndex(
            model_name="canvasedge",
            index=models.Index(fields=["to_node"], name="ddpui_canva_to_node_97fbf7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="canvasedge",
            unique_together={("from_node", "to_node")},
        ),
    ]
