# Generated by Django 4.2 on 2025-11-17 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0139_add_orgfeatureflag_uniqueness_constraints"),
        ("ddpui", "0141_orguser_work_domain"),
    ]

    operations = []
