# Generated by Django 4.2 on 2025-12-04 09:40

from django.db import migrations, models
import django.db.models.deletion
from ddpui.ddpprefect import DBTCLIPROFILE, DBTCLOUDCREDS


def populate_block_references(apps, schema_editor):
    """
    Populate cli_profile_block and dbtcloud_creds_block for existing OrgDbt records.
    For each OrgDbt, find the Org that references it, then find the corresponding
    OrgPrefectBlockv1 records for that Org.
    """
    OrgDbt = apps.get_model("ddpui", "OrgDbt")
    Org = apps.get_model("ddpui", "Org")
    OrgPrefectBlockv1 = apps.get_model("ddpui", "OrgPrefectBlockv1")

    for orgdbt in OrgDbt.objects.all():
        # Find the org that references this OrgDbt
        org = Org.objects.filter(dbt=orgdbt).first()
        if org:
            # Find the cli profile block for this org
            cli_profile_block = OrgPrefectBlockv1.objects.filter(
                org=org, block_type=DBTCLIPROFILE
            ).first()
            if cli_profile_block:
                orgdbt.cli_profile_block = cli_profile_block
            else:
                # Find the dbt cloud creds block for this org
                dbtcloud_creds_block = OrgPrefectBlockv1.objects.filter(
                    org=org, block_type=DBTCLOUDCREDS
                ).first()
                if dbtcloud_creds_block:
                    orgdbt.dbtcloud_creds_block = dbtcloud_creds_block

            orgdbt.save(update_fields=["cli_profile_block", "dbtcloud_creds_block"])


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0142_canvasnode_canvasedge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="branch_name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="cli_profile_block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orgprefectblockv1",
            ),
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="dbtcloud_creds_block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dbtcloud_creds_block",
                to="ddpui.orgprefectblockv1",
            ),
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="is_default_branch",
            field=models.BooleanField(null=True),
        ),
        # Run the data migration to populate block references
        migrations.RunPython(populate_block_references, reverse_code=migrations.RunPython.noop),
    ]
