# Generated by Django 4.2 on 2026-01-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0142_canvasnode_canvasedge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="computation_type",
            field=models.CharField(
                choices=[("raw", "Raw Data"), ("aggregated", "Aggregated Data")],
                default="aggregated",
                max_length=20,
            ),
        ),
    ]
