# Generated by Django 4.2 on 2025-12-01 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ddpui", "0142_canvasnode_canvasedge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                (
                    "organization_logo",
                    models.BinaryField(
                        blank=True, help_text="Organization logo image data", null=True
                    ),
                ),
                (
                    "organization_logo_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename of the uploaded logo",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "organization_logo_content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the logo file",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ai_data_sharing_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Allow sharing organization data with AI for better contextual responses",
                    ),
                ),
                (
                    "ai_logging_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="User has acknowledged that AI questions and answers are logged and stored for at least 3 months",
                    ),
                ),
                (
                    "ai_settings_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When AI settings were last accepted/modified",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_settings_accepted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last accepted/modified AI settings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="ddpui.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
                "db_table": "ddpui_org_settings",
            },
        ),
        migrations.CreateModel(
            name="AIChatMetering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dashboard_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Dashboard ID if request is dashboard-specific",
                        null=True,
                    ),
                ),
                (
                    "chart_id",
                    models.CharField(
                        blank=True,
                        help_text="Chart ID if request is chart-specific",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="Chat session identifier", max_length=100),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="AI model used (e.g., 'openai-gpt-4', 'anthropic-claude')",
                        max_length=100,
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, help_text="Number of tokens in the prompt"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, help_text="Number of tokens in the completion"),
                ),
                ("total_tokens", models.IntegerField(default=0, help_text="Total tokens used")),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                (
                    "include_data",
                    models.BooleanField(
                        default=False, help_text="Whether data was included in the request"
                    ),
                ),
                (
                    "max_rows",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum rows included if data sharing enabled",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When this request was made"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this usage belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat Metering",
                "verbose_name_plural": "AI Chat Metering",
                "db_table": "ai_chat_metering",
            },
        ),
        migrations.CreateModel(
            name="AIChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dashboard_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Dashboard ID if chat is dashboard-specific",
                        null=True,
                    ),
                ),
                (
                    "chart_id",
                    models.CharField(
                        blank=True,
                        help_text="Chart ID if chat is chart-specific",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="Chat session identifier", max_length=100),
                ),
                (
                    "user_prompt",
                    models.TextField(help_text="The user's original question or prompt"),
                ),
                (
                    "ai_response",
                    models.TextField(help_text="The AI's complete response to the user prompt"),
                ),
                (
                    "request_timestamp",
                    models.DateTimeField(help_text="When the user sent the request"),
                ),
                (
                    "response_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the AI response was completed",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this chat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat Log",
                "verbose_name_plural": "AI Chat Logs",
                "db_table": "ai_chat_log",
            },
        ),
        migrations.AddIndex(
            model_name="aichatmetering",
            index=models.Index(fields=["org", "timestamp"], name="ai_chat_met_org_id_13f21e_idx"),
        ),
        migrations.AddIndex(
            model_name="aichatmetering",
            index=models.Index(fields=["user", "timestamp"], name="ai_chat_met_user_id_da9c81_idx"),
        ),
        migrations.AddIndex(
            model_name="aichatmetering",
            index=models.Index(
                fields=["model_used", "timestamp"], name="ai_chat_met_model_u_8fe1cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(
                fields=["org", "response_timestamp"], name="ai_chat_log_org_id_09787e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(
                fields=["user", "response_timestamp"], name="ai_chat_log_user_id_191c04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(fields=["session_id"], name="ai_chat_log_session_58a148_idx"),
        ),
    ]
