# Generated by Django 4.2 on 2025-11-17 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0140_org_website"),
        ("ddpui", "0142_merge_20251117_1358"),
    ]

    operations = []
