# Generated by Django 4.2 on 2025-12-04 11:17

from django.db import migrations, models
import django.db.models.deletion
from ddpui.models.tasks import TaskType


def populate_orgtask_dbt(apps, schema_editor):
    """
    Populate the dbt field for existing OrgTask records.
    Only for tasks of type 'dbt', 'git', or 'edr'.
    For each OrgTask, find the Org it belongs to, then get the OrgDbt
    associated with that Org and link it to the OrgTask.
    """
    OrgTask = apps.get_model("ddpui", "OrgTask")

    for orgtask in OrgTask.objects.filter(
        task__type__in=[TaskType.DBT, TaskType.GIT, TaskType.EDR]
    ):
        org = orgtask.org
        if org and org.dbt:
            orgtask.dbt = org.dbt
            orgtask.save(update_fields=["dbt"])


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0143_orgdbt_branch_name_orgdbt_cli_profile_block_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgtask",
            name="dbt",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ddpui.orgdbt"
            ),
        ),
        # Run the data migration to populate dbt references
        migrations.RunPython(populate_orgtask_dbt, reverse_code=migrations.RunPython.noop),
    ]
