# Generated by Django 4.2 on 2026-01-12 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0143_alter_chart_computation_type"),
        ("ddpui", "0145_recreate_canvaslock_for_dbt_mapping"),
    ]

    operations = []
