# Generated by Django 4.2 on 2026-01-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0146_merge_20260112_0935"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="last_visited_transform_tab",
            field=models.CharField(
                blank=True,
                choices=[("ui", "UI Transform"), ("github", "DBT Transform")],
                max_length=10,
                null=True,
            ),
        ),
    ]
