# Generated by Django 4.2 on 2026-01-15 17:23

from django.db import migrations, models


def set_existing_orgs_to_ddp(apps, schema_editor):
    """Set all existing orgs to use the 'ddp' queue"""
    Org = apps.get_model("ddpui", "Org")
    Org.objects.all().update(prefect_ddp_sync_queue="ddp")


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0147_add_last_visited_transform_tab_to_user_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="prefect_ddp_sync_queue",
            field=models.CharField(
                default="bootcamp-ddp",
                help_text="Work queue for Airbyte/pipeline deployments. New orgs default to 'bootcamp-ddp'.",
                max_length=100,
            ),
        ),
        migrations.RunPython(set_existing_orgs_to_ddp, reverse_code=migrations.RunPython.noop),
    ]
