# Generated by Django 4.2 on 2026-01-18 13:02

import ddpui.models.org
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0147_add_last_visited_transform_tab_to_user_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="queue_config",
            field=models.JSONField(
                default=ddpui.models.org.get_default_queue_config,
                help_text="Queue configuration for different task types (scheduled_pipeline_queue, connection_sync_queue, transform_task_queue)",
            ),
        ),
    ]
