# Generated by Django 4.2 on 2026-01-18 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0143_orgsettings_aichatmetering_aichatlog_and_more"),
        ("ddpui", "0147_add_last_visited_transform_tab_to_user_preferences"),
    ]

    operations = []
