# Generated by Django 4.2 on 2026-02-04 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0148_org_queue_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="ses_whitelisted_email",
        ),
    ]
