# Generated by Django 4.2 on 2026-01-19 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0148_merge_20260118_1212"),
        ("ddpui", "0148_org_queue_config"),
    ]

    operations = []
