# Generated by Django 4.2 on 2026-02-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0149_remove_org_ses_whitelisted_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbytejob",
            name="ended_at",
            field=models.DateTimeField(null=True),
        ),
    ]
