# Generated by Django 4.2 on 2025-11-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0149_update_org_settings_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
