# Generated by Django 4.2 on 2026-03-12 05:56

import os
import ddpui.models.org
from django.db import migrations, models


def backfill_edr_queue_config(apps, schema_editor):
    """
    Add edr_queue configuration to existing organizations that don't have it.
    """
    Org = apps.get_model("ddpui", "Org")

    # Default values for edr_queue
    default_workpool = os.getenv("PREFECT_WORKER_POOL_NAME") or "default"
    edr_queue_config = {"name": "edr", "workpool": default_workpool}

    updated_count = 0
    total_count = Org.objects.count()

    for org in Org.objects.all():
        # Get current queue_config
        current_config = org.queue_config or {}

        # Check if edr_queue already exists
        if "edr_queue" not in current_config:
            # Add edr_queue to the configuration
            current_config["edr_queue"] = edr_queue_config
            org.queue_config = current_config
            org.save(update_fields=["queue_config"])
            updated_count += 1

    print(f"Backfilled edr_queue for {updated_count} out of {total_count} organizations")


def reverse_backfill_edr_queue_config(apps, schema_editor):
    """
    Remove edr_queue configuration from organizations (reverse migration).
    """
    Org = apps.get_model("ddpui", "Org")

    updated_count = 0
    total_count = Org.objects.count()

    for org in Org.objects.all():
        # Get current queue_config
        current_config = org.queue_config or {}

        # Remove edr_queue if it exists
        if "edr_queue" in current_config:
            del current_config["edr_queue"]
            org.queue_config = current_config
            org.save(update_fields=["queue_config"])
            updated_count += 1

    print(f"Removed edr_queue from {updated_count} out of {total_count} organizations")


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0150_alter_airbytejob_ended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="queue_config",
            field=models.JSONField(
                default=ddpui.models.org.get_default_queue_config,
                help_text="Queue configuration for different task types (scheduled_pipeline_queue, connection_sync_queue, transform_task_queue, edr_queue)",
            ),
        ),
        migrations.RunPython(
            backfill_edr_queue_config,
            reverse_backfill_edr_queue_config,
        ),
    ]
