# Generated by Django 4.2 on 2026-02-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0150_alter_airbytejob_ended_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="User-provided title for this snapshot", max_length=255
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start of reporting period (inclusive)"),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="End of reporting period (inclusive). NULL = till today (rolling).",
                        null=True,
                    ),
                ),
                (
                    "frozen_config",
                    models.JSONField(help_text="Frozen dashboard config at snapshot time"),
                ),
                (
                    "frozen_filters",
                    models.JSONField(
                        default=list, help_text="Frozen dashboard filter configs at snapshot time"
                    ),
                ),
                (
                    "frozen_chart_configs",
                    models.JSONField(
                        default=dict, help_text="Frozen chart configs keyed by chart_id"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Executive summary or notes displayed above the dashboard",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "GENERATED"),
                            ("viewed", "VIEWED"),
                            ("archived", "ARCHIVED"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this snapshot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "db_table": "report_snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(fields=["org", "created_at"], name="report_snap_org_id_aee661_idx"),
        ),
    ]
