# Generated by Django 4.2 on 2026-03-12 05:56

import ddpui.models.org
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0150_alter_airbytejob_ended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="queue_config",
            field=models.JSONField(
                default=ddpui.models.org.get_default_queue_config,
                help_text="Queue configuration for different task types (scheduled_pipeline_queue, connection_sync_queue, transform_task_queue, edr_queue)",
            ),
        ),
    ]
