# Generated by Django 4.2 on 2025-11-18 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ddpui", "0150_alter_orgsettings_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatMetering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dashboard_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Dashboard ID if request is dashboard-specific",
                        null=True,
                    ),
                ),
                (
                    "chart_id",
                    models.CharField(
                        blank=True,
                        help_text="Chart ID if request is chart-specific",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="Chat session identifier", max_length=100),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="AI model used (e.g., 'openai-gpt-4', 'anthropic-claude')",
                        max_length=100,
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, help_text="Number of tokens in the prompt"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, help_text="Number of tokens in the completion"),
                ),
                ("total_tokens", models.IntegerField(default=0, help_text="Total tokens used")),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                (
                    "include_data",
                    models.BooleanField(
                        default=False, help_text="Whether data was included in the request"
                    ),
                ),
                (
                    "max_rows",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum rows included if data sharing enabled",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When this request was made"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this usage belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat Metering",
                "verbose_name_plural": "AI Chat Metering",
                "db_table": "ai_chat_metering",
            },
        ),
        migrations.CreateModel(
            name="AIChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dashboard_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Dashboard ID if chat is dashboard-specific",
                        null=True,
                    ),
                ),
                (
                    "chart_id",
                    models.CharField(
                        blank=True,
                        help_text="Chart ID if chat is chart-specific",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="Chat session identifier", max_length=100),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("user_prompt", "User Prompt"), ("ai_response", "AI Response")],
                        help_text="Type of message being logged",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="The actual message content")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When this message was created"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this chat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat Log",
                "verbose_name_plural": "AI Chat Logs",
                "db_table": "ai_chat_log",
            },
        ),
        migrations.AddIndex(
            model_name="aichatmetering",
            index=models.Index(fields=["org", "timestamp"], name="ai_chat_met_org_id_13f21e_idx"),
        ),
        migrations.AddIndex(
            model_name="aichatmetering",
            index=models.Index(fields=["user", "timestamp"], name="ai_chat_met_user_id_da9c81_idx"),
        ),
        migrations.AddIndex(
            model_name="aichatmetering",
            index=models.Index(
                fields=["model_used", "timestamp"], name="ai_chat_met_model_u_8fe1cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(fields=["org", "timestamp"], name="ai_chat_log_org_id_466f09_idx"),
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(fields=["user", "timestamp"], name="ai_chat_log_user_id_3ad059_idx"),
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(fields=["session_id"], name="ai_chat_log_session_58a148_idx"),
        ),
    ]
