# Generated by Django 4.2 on 2026-02-11 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0149_merge_0148_merge_20260118_1212_0148_org_queue_config"),
        ("ddpui", "0150_alter_airbytejob_ended_at"),
    ]

    operations = []
