# Generated by Django 4.2 on 2026-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0151_reportsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsnapshot",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="last_public_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="public_access_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="public_disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="public_share_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="public_shared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
