# Generated by Django 4.2 on 2026-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0151_alter_org_queue_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="is_repo_managed_by_system",
            field=models.BooleanField(
                default=False,
                help_text="True if this repository is created and managed by the system, False if it's a user-owned repository",
            ),
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="ownership_transfer_requested",
            field=models.BooleanField(
                default=False,
                help_text="True if the organization has requested to transfer ownership of the managed repository",
            ),
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="ownership_transfer_requested_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when ownership transfer was requested", null=True
            ),
        ),
    ]
