# Generated by Django 4.2 on 2026-03-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0151_alter_org_queue_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="User-provided title for this snapshot", max_length=255
                    ),
                ),
                (
                    "date_column",
                    models.JSONField(
                        default=dict,
                        help_text="Selected datetime column: {schema_name, table_name, column_name}",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="Start of reporting period (inclusive). NULL = no lower bound.",
                        null=True,
                    ),
                ),
                ("period_end", models.DateField(help_text="End of reporting period (inclusive)")),
                (
                    "frozen_dashboard",
                    models.JSONField(
                        default=dict, help_text="Frozen dashboard config + filters at snapshot time"
                    ),
                ),
                (
                    "frozen_chart_configs",
                    models.JSONField(
                        default=dict, help_text="Frozen chart configs keyed by chart_id"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Executive summary or notes displayed above the dashboard",
                        null=True,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "public_share_token",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("public_shared_at", models.DateTimeField(blank=True, null=True)),
                ("public_disabled_at", models.DateTimeField(blank=True, null=True)),
                ("public_access_count", models.IntegerField(default=0)),
                ("last_public_accessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this snapshot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "db_table": "report_snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(fields=["org", "created_at"], name="report_snap_org_id_aee661_idx"),
        ),
    ]
