# Generated by Django 4.2 on 2026-03-19 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ddpui', '0151_alter_org_queue_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdbt',
            name='docs_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgdbt',
            name='vector_last_ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='ai_data_sharing_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='ai_data_sharing_consented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_data_sharing_consents', to='ddpui.orguser'),
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='ai_data_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrgAIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_context', to='ddpui.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_ai_context_updates', to='ddpui.orguser')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddpui.dashboard')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddpui.org')),
                ('orguser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddpui.orguser')),
            ],
            options={
                'db_table': 'dashboard_chat_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('sequence_number', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'USER'), ('assistant', 'ASSISTANT')], max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('client_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ddpui.dashboardchatsession')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_context', to='ddpui.dashboard')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_ai_context_updates', to='ddpui.orguser')),
            ],
        ),
        migrations.AddIndex(
            model_name='dashboardchatsession',
            index=models.Index(fields=['org', 'dashboard', 'created_at'], name='dchat_sess_org_dash_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboardchatmessage',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_number'), name='dchat_message_session_seq_unique'),
        ),
    ]
