# Generated by Django 4.2 on 2025-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0152_update_ai_chat_log_structure"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aichatlog",
            name="ai_chat_log_org_id_466f09_idx",
        ),
        migrations.RemoveIndex(
            model_name="aichatlog",
            name="ai_chat_log_user_id_3ad059_idx",
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(
                fields=["org", "response_timestamp"], name="ai_chat_log_org_id_09787e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatlog",
            index=models.Index(
                fields=["user", "response_timestamp"], name="ai_chat_log_user_id_191c04_idx"
            ),
        ),
    ]
