# Generated by Django 4.2 on 2026-03-20 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0152_orgdbt_docs_generated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardchatmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="dashboardchatsession",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="dashboardchatmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(client_message_id__isnull=False),
                fields=("session", "client_message_id"),
                name="dchat_message_session_client_msg_unique",
            ),
        ),
    ]
