# Generated by Django 4.2 on 2026-03-14 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0151_alter_org_queue_config"),
        ("ddpui", "0152_reportsnapshot"),
    ]

    operations = []
