# Generated by Django 4.2 on 2026-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0152_reportsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgpreferences",
            name="dashboard_logo_url",
            field=models.URLField(
                blank=True,
                help_text="URL of logo image displayed on all native dashboards",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="dashboard_logo_width",
            field=models.IntegerField(
                default=80, help_text="Logo display width in pixels (40-200)"
            ),
        ),
    ]
