# Generated by Django 4.2 on 2026-03-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0153_add_dashboard_branding_to_orgpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgpreferences",
            name="chart_palette_colors",
            field=models.JSONField(
                blank=True,
                help_text="Array of hex color strings for the active chart palette",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="chart_palette_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the active color palette (preset name, 'custom', or 'logo-derived')",
                max_length=50,
                null=True,
            ),
        ),
    ]
