# Generated by Django 4.2 on 2026-03-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0153_merge_20260314_1816"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReadStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("report", "Report"), ("chart", "Chart")], max_length=20
                    ),
                ),
                (
                    "chart_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Chart ID within frozen_chart_configs (for chart-level read status)",
                        null=True,
                    ),
                ),
                ("last_read_at", models.DateTimeField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_read_statuses",
                        to="ddpui.reportsnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_read_statuses",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "comment_read_status",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("chart", "Chart"), ("report", "Report")], max_length=20
                    ),
                ),
                (
                    "snapshot_chart_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Chart ID within frozen_chart_configs (not a FK)",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Comment text, max 5000 chars enforced at schema level"
                    ),
                ),
                (
                    "mentioned_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of email addresses mentioned in this comment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_authored",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ddpui.reportsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commentreadstatus",
            index=models.Index(fields=["user", "snapshot"], name="comment_rea_user_id_26dfde_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="commentreadstatus",
            unique_together={("user", "snapshot", "target_type", "chart_id")},
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["org", "created_at"], name="comment_org_id_1dc330_idx"),
        ),
    ]
