# Generated by Django 4.2 on 2026-03-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0153_merge_20260314_1816"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("chart", "Chart"),
                            ("report", "Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "snapshot_chart_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Chart ID within frozen_chart_configs (not a FK)",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Comment text, max 5000 chars enforced at schema level"
                    ),
                ),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_authored",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ddpui.chart",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ddpui.dashboard",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="ddpui.comment",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ddpui.reportsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentReadStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("report", "Report"), ("chart", "Chart")], max_length=20
                    ),
                ),
                (
                    "chart_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Chart ID within frozen_chart_configs (for chart-level read status)",
                        null=True,
                    ),
                ),
                ("last_read_at", models.DateTimeField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_read_statuses",
                        to="ddpui.reportsnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_read_statuses",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "comment_read_status",
            },
        ),
        migrations.CreateModel(
            name="CommentMention",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="ddpui.comment",
                    ),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_mentions",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "comment_mention",
            },
        ),
        migrations.AddIndex(
            model_name="commentreadstatus",
            index=models.Index(fields=["user", "snapshot"], name="comment_rea_user_id_26dfde_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="commentreadstatus",
            unique_together={("user", "snapshot", "target_type", "chart_id")},
        ),
        migrations.AlterUniqueTogether(
            name="commentmention",
            unique_together={("comment", "mentioned_user")},
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["dashboard", "created_at"], name="comment_dashboa_911024_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["chart", "created_at"], name="comment_chart_i_d2f491_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment", "created_at"], name="comment_parent__a338b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["org", "created_at"], name="comment_org_id_1dc330_idx"),
        ),
    ]
