# Generated by Django 4.2 on 2026-03-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0154_commentreadstatus_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
