# Generated by Django 4.2 on 2026-03-15 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0154_comment_commentreadstatus_commentmention_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="position_x",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="position_y",
        ),
    ]
