# Generated by Django 4.2 on 2026-03-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0154_commentreadstatus_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="target_type",
            field=models.CharField(
                choices=[("chart", "Chart"), ("summary", "Summary")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="commentreadstatus",
            name="target_type",
            field=models.CharField(
                choices=[("chart", "Chart"), ("summary", "Summary")], max_length=20
            ),
        ),
    ]
