# Generated by Django 4.2 on 2026-04-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0154_add_chart_palette_to_orgpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="theme_background_color",
            field=models.CharField(
                blank=True,
                help_text="Background color in hex format (e.g., #ffffff)",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="theme_background_gradient",
            field=models.JSONField(
                blank=True,
                help_text="Background gradient configuration as JSON object with type, colors, and direction",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="theme_background_image_blur",
            field=models.IntegerField(
                default=0, help_text="Blur intensity for background image (0-20)"
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="theme_background_image_url",
            field=models.URLField(
                blank=True, help_text="URL of background image for the dashboard", null=True
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="theme_chart_opacity",
            field=models.FloatField(default=1.0, help_text="Opacity of chart components (0.0-1.0)"),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="theme_overlay_color",
            field=models.CharField(
                blank=True,
                help_text="Overlay color in hex format for translucent effect",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="theme_overlay_opacity",
            field=models.FloatField(default=0.0, help_text="Opacity of overlay (0.0-1.0)"),
        ),
    ]
