# Generated by Django 4.2 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0155_add_dashboard_theming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="theme_background_color",
            field=models.CharField(
                blank=True,
                help_text="Background color in hex format (e.g., #ffffff or #ffffffff)",
                max_length=9,
                null=True,
            ),
        ),
    ]
