# Generated by Django 4.2 on 2026-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0154_dashboardchatprompttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardchatsession",
            name="vector_collection_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
