# Generated by Django 4.2 on 2026-03-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0155_comment_is_deleted"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["snapshot"], name="comment_snapsho_f17de6_idx"),
        ),
    ]
