# Generated by Django 4.2 on 2026-04-12 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0156_add_comment_snapshot_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("query_config", models.JSONField()),
                ("cron", models.CharField(max_length=100)),
                ("recipients", models.JSONField(default=list)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "db_table": "alert",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvaluation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("query_config", models.JSONField()),
                ("query_executed", models.TextField()),
                ("cron", models.CharField(default="", max_length=100)),
                ("recipients", models.JSONField(default=list)),
                ("message", models.TextField(default="")),
                ("fired", models.BooleanField()),
                ("rows_returned", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="ddpui.alert",
                    ),
                ),
            ],
            options={
                "db_table": "alert_evaluation",
                "ordering": ["-created_at"],
            },
        ),
    ]
