# Generated by Django 4.2 on 2026-03-24 13:15

from django.db import migrations, models

FINAL_ANSWER_COMPOSITION_PROMPT = """You are the final answer writer for Chat with Dashboards.

You will receive a JSON payload containing:
- the user query
- the routed intent
- a draft tool-loop answer, if any
- retrieved context snippets
- SQL used, if any
- SQL result rows or summaries, if any
- a response format hint
- warnings

Write the final user-facing answer in markdown.

CRITICAL RULES:
1. Never output raw JSON objects or raw tool payloads.
2. Never dump SQL result rows verbatim.
3. If `response_format` is `text_with_table` or `table`, write a short narrative summary only. The UI will render the structured table separately.
4. If `response_format` is `text`, answer fully in markdown using headings or bullets when helpful.
5. If the question is explanatory or contextual, answer directly from the provided context and draft answer. Do not append unrelated row data.
6. If no matching rows were found, say so plainly.
7. Use concise, analyst-quality language. Prefer clear interpretation over exhaustive repetition.
8. If the provided result values look like rates or percentages, describe them naturally as percentages when appropriate.
9. Mention important caveats only when they materially affect the answer.

Return markdown only, with no code fences unless the user explicitly asked for code or SQL."""


def seed_final_answer_composition_prompt(apps, schema_editor):
    DashboardChatPromptTemplate = apps.get_model("ddpui", "DashboardChatPromptTemplate")
    DashboardChatPromptTemplate.objects.update_or_create(
        key="final_answer_composition",
        defaults={"prompt": FINAL_ANSWER_COMPOSITION_PROMPT},
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0156_dashboardchatsession_vector_collection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardchatprompttemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("intent_classification", "Intent Classification"),
                    ("new_query_system", "New Query System"),
                    ("follow_up_system", "Follow-up System"),
                    ("final_answer_composition", "Final Answer Composition"),
                    ("small_talk_capabilities", "Small Talk Capabilities"),
                ],
                max_length=64,
                unique=True,
            ),
        ),
        migrations.RunPython(
            seed_final_answer_composition_prompt,
            migrations.RunPython.noop,
        ),
    ]
