# Generated by Django 4.2 on 2026-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0156_add_comment_snapshot_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="is_repo_managed_by_system",
            field=models.BooleanField(
                default=False,
                help_text="True if this repository is created and managed by the system, False if it's a user-owned repository",
            ),
        ),
    ]
