# Generated by Django 4.2 on 2026-04-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0156_add_comment_snapshot_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsnapshot",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified the summary",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_snapshots",
                to="ddpui.orguser",
            ),
        ),
    ]
