# Generated by Django 4.2 on 2026-04-03 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0153_add_dashboard_tabs"),
        ("ddpui", "0156_add_comment_snapshot_index"),
    ]

    operations = []
