# Generated by Django 4.2 on 2026-04-07 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0156_add_comment_snapshot_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="docs_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="vector_last_ingested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="ai_data_sharing_consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="ai_data_sharing_consented_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_data_sharing_consents",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="ai_data_sharing_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
