# Generated by Django 4.2 on 2026-04-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0157_orgdbt_is_repo_managed_by_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsnapshot",
            name="period_end",
            field=models.DateField(
                blank=True,
                help_text="End of reporting period (inclusive). NULL for snapshots without date filtering.",
                null=True,
            ),
        ),
    ]
