# Generated by Django 4.2 on 2026-04-15 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0157_add_last_modified_by_to_report_snapshot"),
        ("ddpui", "0157_orgdbt_is_repo_managed_by_system"),
    ]

    operations = []
