# Generated by Django 4.2 on 2026-04-25 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    """Migration to add the Admin Audit Log model."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddpui', '0157_orgdbt_is_repo_managed_by_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login')], max_length=10)),
                ('resource_type', models.CharField(help_text='e.g., Organization, Warehouse, FeatureFlag', max_length=100)),
                ('resource_id', models.CharField(help_text='ID of the modified resource', max_length=255)),
                ('payload', models.JSONField(default=dict, help_text='The data payload or diff (MUST be scrubbed of passwords)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(
                    help_text='The admin user who performed the action',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='audit_logs',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'admin_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
