# Generated by Django 4.2 on 2026-04-15 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0153_metric_definition_and_annotation"),
        ("ddpui", "0157_orgdbt_is_repo_managed_by_system"),
    ]

    operations = []
