# Generated by Django 4.2 on 2026-04-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0157_orgdbt_is_repo_managed_by_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("column", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "aggregation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sum", "SUM"),
                            ("avg", "AVG"),
                            ("count", "COUNT"),
                            ("min", "MIN"),
                            ("max", "MAX"),
                            ("count_distinct", "COUNT DISTINCT"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("column_expression", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("target_value", models.FloatField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Increase"), ("decrease", "Decrease")], max_length=10
                    ),
                ),
                ("green_threshold_pct", models.FloatField(default=100.0)),
                ("amber_threshold_pct", models.FloatField(default=80.0)),
                (
                    "time_grain",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_dimension_column", models.CharField(blank=True, max_length=255, null=True)),
                ("trend_periods", models.IntegerField(default=12)),
                (
                    "metric_type_tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("input", "Input"),
                            ("output", "Output"),
                            ("outcome", "Outcome"),
                            ("impact", "Impact"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("program_tags", models.JSONField(blank=True, default=list)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpis",
                        to="ddpui.metric",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "ordering": ["display_order", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="unique_metric_name_per_org"
            ),
        ),
    ]
