# Generated by Django 4.2 on 2026-03-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0157_dashboardchatprompttemplate_final_answer_composition"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardchatmessage",
            name="response_latency_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dashboardchatmessage",
            name="timing_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
