# Generated by Django 4.2 on 2026-04-07 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0157_dashboard_chat_orgdbt_and_org_preferences_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgAIContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("markdown", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context",
                        to="ddpui.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_ai_context_updates",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "org_ai_context",
            },
        ),
        migrations.CreateModel(
            name="DashboardAIContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("markdown", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context",
                        to="ddpui.dashboard",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_ai_context_updates",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_ai_context",
            },
        ),
    ]
