# Generated by Django 4.2 on 2026-05-04 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0158_allow_null_period_end_on_snapshot"),
        ("ddpui", "0158_merge_20260415_1814"),
    ]

    operations = []
