# Generated by Django 4.2 on 2026-04-07 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0158_dashboard_chat_ai_contexts_org_and_dashboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "USER"), ("assistant", "ASSISTANT")], max_length=20
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("client_message_id", models.CharField(blank=True, max_length=100, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[("thumbs_up", "Thumbs Up"), ("thumbs_down", "Thumbs Down")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("response_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("timing_breakdown", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "dashboard_chat_message",
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="DashboardChatPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("intent_classification", "Intent Classification"),
                            ("new_query_system", "New Query System"),
                            ("follow_up_system", "Follow-up System"),
                            ("final_answer_composition", "Final Answer Composition"),
                            ("small_talk_capabilities", "Small Talk Capabilities"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("prompt", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_chat_prompt_template",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="DashboardChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("vector_collection_name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.dashboard",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddpui.orguser"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardChatTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("cancel_requested", "Cancel Requested"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("progress_label", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True, default="")),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assistant_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_turn",
                        to="ddpui.dashboardchatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="ddpui.dashboardchatsession",
                    ),
                ),
                (
                    "user_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn",
                        to="ddpui.dashboardchatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_turn",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="dashboardchatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ddpui.dashboardchatsession",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardchatturn",
            index=models.Index(fields=["session", "status"], name="dchat_turn_session_status_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardchatturn",
            index=models.Index(fields=["created_at"], name="dchat_turn_created_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardchatsession",
            index=models.Index(
                fields=["org", "dashboard", "created_at"], name="dchat_sess_org_dash_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardchatmessage",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence_number"), name="dchat_message_session_seq_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardchatmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_message_id__isnull", False)),
                fields=("session", "client_message_id"),
                name="dchat_message_session_client_msg_unique",
            ),
        ),
    ]
