# Generated by Django 4.2 on 2026-03-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0159_merge_20260504_0910"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="tabs",
            field=models.JSONField(
                default=list,
                help_text="Array of tab objects: [{id, title, layout_config, components}]",
            ),
        ),
    ]
