# Generated by Django 4.2 on 2026-05-10 05:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0159_merge_20260504_0910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncstats",
            name="sync_type",
            field=models.CharField(
                choices=[("manual", "manual"), ("orchestrate", "orchestrate")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("organization_updated", "organization_updated")], max_length=100
                    ),
                ),
                ("old_data", models.JSONField()),
                ("new_data", models.JSONField()),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
        ),
    ]
