# Generated by Django 4.2 on 2026-04-13 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0157_orgdbt_is_repo_managed_by_system"),
        ("ddpui", "0159_dashboard_chat_config_tables"),
    ]

    operations = []
