# Generated by Django 4.2 on 2026-04-06 15:30

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0156_add_comment_snapshot_index"),
        ("ddpui", "0159_dashboardchatprompttemplate_intent_follow_up_refs"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardChatTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("cancel_requested", "Cancel Requested"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "progress_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "cancel_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "assistant_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_turn",
                        to="ddpui.dashboardchatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="ddpui.dashboardchatsession",
                    ),
                ),
                (
                    "user_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn",
                        to="ddpui.dashboardchatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_turn",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dashboardchatturn",
            index=models.Index(
                fields=["session", "status"],
                name="dchat_turn_session_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardchatturn",
            index=models.Index(
                fields=["created_at"],
                name="dchat_turn_created_idx",
            ),
        ),
    ]
