# Generated by Django 4.2 on 2026-05-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add performed_by field to admin audit log."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ddpui", "0160_alter_syncstats_sync_type_adminauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminauditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_admin_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
