# Generated by Django 4.2 on 2026-05-13 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0159_merge_20260504_0910"),
        ("ddpui", "0160_merge_20260413_1732"),
    ]

    operations = []
