# Generated by Django 4.2 on 2026-04-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0160_dashboardchatturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardchatmessage",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[("thumbs_up", "Thumbs Up"), ("thumbs_down", "Thumbs Down")],
                max_length=16,
                null=True,
            ),
        ),
    ]
