# Generated by Django 4.2 on 2026-05-25 11:00

from django.db import migrations, models
import django.db.models.deletion


def copy_comment_target_ids(apps, schema_editor):
    """Copy snapshot_chart_id → target_id on Comment before dropping the old column."""
    Comment = apps.get_model("ddpui", "Comment")
    for comment in Comment.objects.filter(snapshot_chart_id__isnull=False):
        comment.target_id = comment.snapshot_chart_id
        comment.save(update_fields=["target_id"])


def copy_readstatus_target_ids(apps, schema_editor):
    """Copy chart_id → target_id on CommentReadStatus before dropping the old column."""
    CommentReadStatus = apps.get_model("ddpui", "CommentReadStatus")
    for status in CommentReadStatus.objects.filter(chart_id__isnull=False):
        status.target_id = status.chart_id
        status.save(update_fields=["target_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0160_add_dashboard_tabs"),
    ]

    operations = [
        # --- Step 1: Drop old unique constraint on commentreadstatus ---
        migrations.AlterUniqueTogether(
            name="commentreadstatus",
            unique_together=set(),
        ),
        # --- Step 2: Add new target_id columns (nullable) ---
        migrations.AddField(
            model_name="comment",
            name="target_id",
            field=models.IntegerField(
                blank=True, help_text="Entity ID within frozen_chart_configs (not a FK)", null=True
            ),
        ),
        migrations.AddField(
            model_name="commentreadstatus",
            name="target_id",
            field=models.IntegerField(
                blank=True,
                help_text="Entity ID for target-level read status (chart ID, KPI ID, etc.)",
                null=True,
            ),
        ),
        # --- Step 3: Copy data from old columns to new columns ---
        migrations.RunPython(copy_comment_target_ids, migrations.RunPython.noop),
        migrations.RunPython(copy_readstatus_target_ids, migrations.RunPython.noop),
        # --- Step 4: Drop old columns ---
        migrations.RemoveField(
            model_name="comment",
            name="snapshot_chart_id",
        ),
        migrations.RemoveField(
            model_name="commentreadstatus",
            name="chart_id",
        ),
        # --- Step 5: Add new unique constraint ---
        migrations.AlterUniqueTogether(
            name="commentreadstatus",
            unique_together={("user", "snapshot", "target_type", "target_id")},
        ),
        # --- Step 6: Create Metric model ---
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("column", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "aggregation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sum", "SUM"),
                            ("avg", "AVG"),
                            ("count", "COUNT"),
                            ("min", "MIN"),
                            ("max", "MAX"),
                            ("count_distinct", "COUNT DISTINCT"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("column_expression", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        # --- Step 7: Create KPI model ---
        migrations.CreateModel(
            name="KPI",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("target_value", models.FloatField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Increase"), ("decrease", "Decrease")], max_length=10
                    ),
                ),
                ("green_threshold_pct", models.FloatField(default=100.0)),
                ("amber_threshold_pct", models.FloatField(default=80.0)),
                (
                    "time_grain",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_dimension_column", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "metric_type_tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("input", "Input"),
                            ("output", "Output"),
                            ("outcome", "Outcome"),
                            ("impact", "Impact"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("program_tags", models.JSONField(blank=True, default=list)),
                ("annotations", models.JSONField(blank=True, default=list)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpis",
                        to="ddpui.metric",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "ordering": ["display_order", "-updated_at"],
            },
        ),
        # --- Step 8: Add unique constraint on Metric ---
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="unique_metric_name_per_org"
            ),
        ),
    ]
