# Generated by Django 4.2 on 2026-05-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0161_metrics_kpis_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "note_type",
                    models.CharField(
                        choices=[("beneficiary_quote", "Beneficiary Quote"), ("note", "Note")],
                        max_length=20,
                    ),
                ),
                ("period_key", models.CharField(max_length=100)),
                ("period_date", models.DateField(blank=True, null=True)),
                ("content", models.TextField()),
                ("snapshot_value", models.FloatField(blank=True, null=True)),
                ("snapshot_pop_change", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_entries",
                        to="ddpui.kpi",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_date", "-created_at"],
            },
        ),
    ]
