# Generated by Django 4.2 on 2026-05-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0161_metrics_kpis_annotations_alter_commentreadstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kpis_modified",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrics_modified",
                to="ddpui.orguser",
            ),
        ),
    ]
