# Generated by Django 4.2 on 2026-06-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0163_remove_dashboard_root_layout_components"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("metric_threshold", "Metric threshold"),
                            ("kpi_rag", "KPI RAG"),
                            ("standalone", "Standalone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("standalone_config", models.JSONField(blank=True, null=True)),
                ("condition", models.JSONField()),
                ("schedule_cron", models.CharField(max_length=100)),
                ("delivery_channels", models.JSONField(default=list)),
                ("slack_webhook_url", models.TextField(blank=True, null=True)),
                ("message_template", models.TextField()),
                ("recipients", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ddpui.kpi",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts_modified",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ddpui.metric",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ddpui.org",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("scheduled_for", models.DateTimeField()),
                ("evaluated_at", models.DateTimeField()),
                ("value", models.FloatField(blank=True, null=True)),
                ("fired", models.BooleanField()),
                ("alert_snapshot", models.JSONField()),
                ("sql_executed", models.TextField()),
                ("message", models.TextField()),
                ("deliveries", models.JSONField(default=list)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ddpui.alert",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(
                fields=["alert", "-evaluated_at"], name="ddpui_alert_alert_i_fc3fca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(
                fields=["alert", "-evaluated_at", "fired"], name="ddpui_alert_alert_i_7ba43b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["org", "is_active"], name="ddpui_alert_org_id_44378d_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["is_active", "last_evaluated_at"], name="ddpui_alert_is_acti_d1dea9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="unique_alert_name_per_org"
            ),
        ),
    ]
