# Generated by Django 4.2 on 2026-06-12 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0163_remove_dashboard_root_layout_components"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "USER"), ("assistant", "ASSISTANT")], max_length=20
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("client_message_id", models.CharField(blank=True, max_length=100, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[("thumbs_up", "Thumbs Up"), ("thumbs_down", "Thumbs Down")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("response_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("timing_breakdown", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "dashboard_chat_message",
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="DashboardChatPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("intent_classification", "Intent Classification"),
                            ("new_query_system", "New Query System"),
                            ("follow_up_system", "Follow-up System"),
                            ("sql_verification", "SQL Verification"),
                            ("final_answer_composition", "Final Answer Composition"),
                            ("small_talk_capabilities", "Small Talk Capabilities"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("prompt", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_chat_prompt_template",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="DashboardChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.dashboard",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddpui.orguser"
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="orgdbt",
            name="docs_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="ai_data_sharing_consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="ai_data_sharing_consented_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_data_sharing_consents",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="ai_data_sharing_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="dashboard_chat_share_pii_with_llms",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="OrgAIContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("markdown", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context",
                        to="ddpui.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_ai_context_updates",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "org_ai_context",
            },
        ),
        migrations.CreateModel(
            name="DashboardChatTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("cancel_requested", "Cancel Requested"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("progress_label", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True, default="")),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assistant_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_turn",
                        to="ddpui.dashboardchatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="ddpui.dashboardchatsession",
                    ),
                ),
                (
                    "user_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn",
                        to="ddpui.dashboardchatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_turn",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardChatPIIColumnOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("schema_name", models.CharField(blank=True, default="", max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("column_name", models.CharField(max_length=255)),
                ("pii", models.BooleanField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_chat_pii_column_overrides",
                        to="ddpui.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_chat_pii_column_overrides",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_pii_column_override",
            },
        ),
        migrations.CreateModel(
            name="DashboardChatMetadataBuildRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("building", "Building"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        default="building",
                        max_length=16,
                    ),
                ),
                ("builder_model", models.CharField(blank=True, default="", max_length=128)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("log_payload", models.JSONField(blank=True, null=True)),
                ("error_payload", models.JSONField(blank=True, null=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_metadata_build_runs",
                        to="ddpui.dashboard",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_metadata_build_run",
            },
        ),
        migrations.CreateModel(
            name="DashboardChatMetadataArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("schema_version", models.PositiveIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("building", "Building"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        default="stale",
                        max_length=16,
                    ),
                ),
                ("artifact_json", models.JSONField(blank=True, default=dict)),
                ("source_fingerprint", models.CharField(blank=True, default="", max_length=255)),
                ("builder_model", models.CharField(blank=True, default="", max_length=128)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("error_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "built_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_chat_metadata_builds",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_metadata_artifact",
                        to="ddpui.dashboard",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_chat_metadata_artifact",
            },
        ),
        migrations.AddField(
            model_name="dashboardchatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ddpui.dashboardchatsession",
            ),
        ),
        migrations.CreateModel(
            name="DashboardAIContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("markdown", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context",
                        to="ddpui.dashboard",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_ai_context_updates",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_ai_context",
            },
        ),
        migrations.AddIndex(
            model_name="dashboardchatturn",
            index=models.Index(fields=["session", "status"], name="dchat_turn_session_status_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardchatturn",
            index=models.Index(fields=["created_at"], name="dchat_turn_created_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardchatsession",
            index=models.Index(
                fields=["org", "dashboard", "created_at"], name="dchat_sess_org_dash_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardchatpiicolumnoverride",
            index=models.Index(
                fields=["org", "schema_name", "table_name"], name="dchat_pii_override_table_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardchatpiicolumnoverride",
            constraint=models.UniqueConstraint(
                fields=("org", "schema_name", "table_name", "column_name"),
                name="dchat_pii_override_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardchatmetadatabuildrun",
            index=models.Index(fields=["dashboard", "started_at"], name="dchat_meta_run_dash_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardchatmetadatabuildrun",
            index=models.Index(fields=["status"], name="dchat_meta_run_status_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardchatmetadataartifact",
            index=models.Index(fields=["status"], name="dchat_meta_artifact_status_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardchatmetadataartifact",
            index=models.Index(fields=["built_at"], name="dchat_meta_artifact_built_idx"),
        ),
        migrations.AddConstraint(
            model_name="dashboardchatmessage",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence_number"), name="dchat_message_session_seq_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardchatmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_message_id__isnull", False)),
                fields=("session", "client_message_id"),
                name="dchat_message_session_client_msg_unique",
            ),
        ),
    ]
