# Generated by Django 4.2 on 2026-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0164_alert_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="orguser",
            name="has_seen_rbac_notice",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has seen the one-time RBAC v2 migration notice",
            ),
        ),
    ]
