# Generated by Django 4.2 on 2026-06-18 15:21

from django.db import migrations, models
import django.db.models.deletion


def _backfill_owners(apps, schema_editor):
    """Set owner = created_by where set; else oldest active Admin in the same org."""
    OrgUser = apps.get_model("ddpui", "OrgUser")
    Role = apps.get_model("ddpui", "Role")

    try:
        admin_role = Role.objects.get(slug="admin")
    except Role.DoesNotExist:
        admin_role = None

    def oldest_admin_for_org(org_id):
        if admin_role is None:
            return None
        return OrgUser.objects.filter(org_id=org_id, new_role=admin_role).order_by("id").first()

    MODELS = [
        apps.get_model("ddpui", "Dashboard"),
        apps.get_model("ddpui", "Chart"),
        apps.get_model("ddpui", "ReportSnapshot"),
        apps.get_model("ddpui", "Metric"),
        apps.get_model("ddpui", "KPI"),
    ]

    for Model in MODELS:
        for resource in Model.objects.select_related("created_by", "org").iterator():
            if resource.created_by_id is not None:
                resource.owner_id = resource.created_by_id
            else:
                fallback = oldest_admin_for_org(resource.org_id)
                resource.owner_id = fallback.id if fallback else None
            resource.save(update_fields=["owner"])


def _reverse_backfill_owners(apps, schema_editor):
    pass  # AddField reverse drops the column; no data to restore


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0165_collapse_roles_rbac_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_charts",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_dashboards",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="kpi",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_kpis",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_metrics",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_reports",
                to="ddpui.orguser",
            ),
        ),
        migrations.RunPython(_backfill_owners, _reverse_backfill_owners),
    ]
