# Generated by Django 4.2 on 2026-07-03 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0166_kpi_extra_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatWithDataSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="New chat", max_length=255)),
                ("thread_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="ddpui.org",
                    ),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="ddpui.orguser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatWithDataTurnAudit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("user_message", models.TextField()),
                ("sql_queries", models.JSONField(default=list)),
                ("tools_called", models.JSONField(default=list)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(null=True)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_turn_audits",
                        to="ddpui.org",
                    ),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddpui.orguser"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn_audits",
                        to="ddpui.chatwithdatasession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatWithDataOrgConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("allowed_schemas", models.JSONField(blank=True, null=True)),
                ("max_result_rows", models.IntegerField(default=100)),
                ("query_timeout_s", models.IntegerField(default=30)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_with_data_config",
                        to="ddpui.org",
                    ),
                ),
            ],
        ),
    ]
