# Generated by Django 4.2 on 2026-07-17 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0166_kpi_extra_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialClone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trial_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("running", "RUNNING"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=100, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("timings", models.JSONField(default=dict)),
                ("manifest", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ddpui.org",
                    ),
                ),
                (
                    "trial_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ddpui.org",
                    ),
                ),
            ],
        ),
    ]
