# Generated by Django 4.2 on 2026-06-29 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0165_orguser_has_seen_rbac_notice"),
        ("ddpui", "0166_kpi_extra_config"),
    ]

    operations = []
