# Generated by Django 4.2 on 2026-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0167_chat_with_data_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwithdataturnaudit",
            name="intent",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatwithdataturnaudit",
            name="validation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
