# Generated by Django 4.2 on 2026-07-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0167_orguser_has_seen_rbac_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts_created",
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="last_modified_by",
            field=models.ForeignKey(
                db_column="last_modified_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_modified_by",
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="last_modified_by",
            field=models.ForeignKey(
                db_column="last_modified_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboards_modified",
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kpis_created",
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrics_created",
                to="ddpui.orguser",
            ),
        ),
    ]
