# Generated by Django 4.2 on 2026-07-10 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddpui', '0167_orguser_has_seen_rbac_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgwarehouse',
            name='secret_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ddpui.orgprefectblockv1'),
        ),
    ]
