# Generated by Django 4.2 on 2026-07-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0167_orguser_has_seen_rbac_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="general_audience",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("admins", "Admins"),
                    ("analysts_plus", "Analysts Plus"),
                    ("all_users", "All Users"),
                ],
                default="all_users",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="general_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="general_audience",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("admins", "Admins"),
                    ("analysts_plus", "Analysts Plus"),
                    ("all_users", "All Users"),
                ],
                default="all_users",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="general_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="kpi",
            name="general_audience",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("admins", "Admins"),
                    ("analysts_plus", "Analysts Plus"),
                    ("all_users", "All Users"),
                ],
                default="all_users",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="kpi",
            name="general_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="kpi",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="general_audience",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("admins", "Admins"),
                    ("analysts_plus", "Analysts Plus"),
                    ("all_users", "All Users"),
                ],
                default="all_users",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="general_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="ddpui.orguser",
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="allow_public_sharing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_general_audience",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("admins", "Admins"),
                    ("analysts_plus", "Analysts Plus"),
                    ("all_users", "All Users"),
                ],
                default="all_users",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_general_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="general_audience",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("admins", "Admins"),
                    ("analysts_plus", "Analysts Plus"),
                    ("all_users", "All Users"),
                ],
                default="all_users",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="general_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="owner",
            field=models.ForeignKey(
                help_text="Current owner of this snapshot for delete/transfer purposes",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts_created",
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kpis_created",
                to="ddpui.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metrics_created",
                to="ddpui.orguser",
            ),
        ),
    ]
