# Generated by Django 4.2 on 2026-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0168_alter_alert_created_by_alter_chart_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="False deactivates the org: its users are blocked at permission-load. Reversible.",
            ),
        ),
    ]
