# Generated by Django 4.2 on 2026-07-22 16:59

import ddpui.models.org_user
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0168_alter_alert_created_by_alter_chart_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddpui.orguser"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_groups",
                        to="ddpui.org",
                    ),
                ),
            ],
            options={
                "db_table": "orguser_group",
            },
        ),
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(default=ddpui.models.org_user.default_invitation_expiry),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="allow_public_sharing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_analyst_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_member_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit")], default="view", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("bar", "Bar Chart"),
                    ("pie", "Pie Chart"),
                    ("line", "Line Chart"),
                    ("number", "Number Chart"),
                    ("map", "Map Chart"),
                    ("table", "Table Chart"),
                    ("pivot_table", "Pivot Table"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ResourceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource_type", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=255)),
                (
                    "principal_type",
                    models.CharField(choices=[("user", "User"), ("group", "Group")], max_length=5),
                ),
                ("principal_id", models.BigIntegerField()),
                (
                    "access_level",
                    models.CharField(choices=[("view", "View"), ("edit", "Edit")], max_length=5),
                ),
                ("pending_email", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_shares_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "db_table": "resource_share",
            },
        ),
        migrations.CreateModel(
            name="OrgUserGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("pending_email", models.CharField(max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="ddpui.orgusergroup",
                    ),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
            ],
            options={
                "db_table": "orguser_group_member",
            },
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["org", "resource_type", "resource_id"], name="resource_sh_org_id_d2b47f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["org", "principal_type", "principal_id"],
                name="resource_sh_org_id_1ff3b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(fields=["pending_email"], name="resource_sh_pending_df14fb_idx"),
        ),
        migrations.AddConstraint(
            model_name="orgusergroupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "pending_email"), name="uq_orguser_group_member_pending_email"
            ),
        ),
    ]
