# Generated by Django 4.2 on 2026-07-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0168_alter_alert_created_by_alter_chart_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgdbt",
            name="dbt_profile_secret_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ddpui.orgprefectblockv1",
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("bar", "Bar Chart"),
                    ("pie", "Pie Chart"),
                    ("line", "Line Chart"),
                    ("number", "Number Chart"),
                    ("map", "Map Chart"),
                    ("table", "Table Chart"),
                    ("pivot_table", "Pivot Table"),
                ],
                max_length=20,
            ),
        ),
    ]
