# Generated by Django 4.2 on 2026-07-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0168_chat_with_data_intent_validation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatWithDataTableCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("card", models.JSONField(default=dict)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("built_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_table_cards",
                        to="ddpui.org",
                    ),
                ),
            ],
            options={
                "unique_together": {("org", "schema_name", "table_name")},
            },
        ),
    ]
