# Generated by Django 4.2 on 2026-07-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0169_backfill_owner_and_general_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource_type", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=255)),
                ("principal_type", models.CharField(max_length=10)),
                ("principal_id", models.BigIntegerField(null=True)),
                ("principal_value", models.CharField(max_length=50, null=True)),
                ("permission", models.CharField(max_length=5)),
                ("status", models.CharField(default="active", max_length=10)),
                ("pending_email", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_shares_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "db_table": "resource_share",
            },
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="resource_sh_resourc_1d676f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["principal_type", "principal_id"], name="resource_sh_princip_57cdf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(fields=["org", "status"], name="resource_sh_org_id_9c19d3_idx"),
        ),
    ]
