# Generated by Django 4.2 on 2026-07-22 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0169_alter_chart_chart_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddpui.orguser"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_groups",
                        to="ddpui.org",
                    ),
                ),
            ],
            options={
                "db_table": "orguser_group",
            },
        ),
        migrations.CreateModel(
            name="OrgUserGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="ddpui.orgusergroup",
                    ),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.invitation",
                    ),
                ),
            ],
            options={
                "db_table": "orguser_group_member",
            },
        ),
        migrations.AddConstraint(
            model_name="orgusergroupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "invitation"), name="uq_orguser_group_member_invitation"
            ),
        ),
    ]
