# Generated by Django 4.2 on 2026-07-23 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ddpui', '0169_alter_chart_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddpui.orguser')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='ddpui.org')),
            ],
            options={
                'db_table': 'orguser_group',
            },
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='allow_public_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='default_analyst_level',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('no_access', 'No Access')], default='view', max_length=10),
        ),
        migrations.AddField(
            model_name='orgpreferences',
            name='default_member_level',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('no_access', 'No Access')], default='view', max_length=10),
        ),
        migrations.CreateModel(
            name='ResourceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=20)),
                ('resource_id', models.CharField(max_length=255)),
                ('principal_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=5, null=True)),
                ('principal_id', models.BigIntegerField(null=True)),
                ('access_level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('no_access', 'No Access')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_shares_created', to='ddpui.orguser')),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddpui.invitation')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddpui.org')),
            ],
            options={
                'db_table': 'resource_share',
            },
        ),
        migrations.CreateModel(
            name='OrgUserGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ddpui.orgusergroup')),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddpui.invitation')),
                ('orguser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ddpui.orguser')),
            ],
            options={
                'db_table': 'orguser_group_member',
            },
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['org', 'resource_type', 'resource_id'], name='resource_sh_org_id_d2b47f_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['org', 'principal_type', 'principal_id'], name='resource_sh_org_id_1ff3b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgusergroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'invitation'), name='uq_orguser_group_member_invitation'),
        ),
    ]
