# Generated by Django 4.2 on 2026-07-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0169_alter_chart_chart_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="ddpui.dashboard",
                    ),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_dashboards",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_favorite",
            },
        ),
        migrations.CreateModel(
            name="ChartFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="ddpui.chart",
                    ),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_charts",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "chart_favorite",
            },
        ),
        migrations.AddConstraint(
            model_name="dashboardfavorite",
            constraint=models.UniqueConstraint(
                fields=("dashboard", "org_user"), name="unique_dashboard_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="chartfavorite",
            constraint=models.UniqueConstraint(
                fields=("chart", "org_user"), name="unique_chart_favorite"
            ),
        ),
    ]
