# Generated by Django 4.2 on 2026-07-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0170_orgdbt_dbt_profile_secret_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgwarehouse",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ddpui.org", unique=True
            ),
        ),
    ]
