# Generated by Django 4.2 on 2026-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0169_chat_with_data_table_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwithdatasession",
            name="scope_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatwithdatasession",
            name="scope_type",
            field=models.CharField(default="org", max_length=20),
        ),
    ]
