# Generated by Django 4.2 on 2026-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0169_chat_with_data_table_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwithdatasession",
            name="scope_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatwithdatasession",
            name="scope_type",
            field=models.CharField(default="org", max_length=20),
        ),
        # Django keeps defaults in Python, not the database. Persist this one at
        # the DB level so inserts from code that predates the column (other
        # branches sharing a dev DB, mid-deploy old processes) don't violate
        # NOT NULL — the exact failure mode we hit with resource-sharing's
        # general_audience column.
        migrations.RunSQL(
            sql="ALTER TABLE ddpui_chatwithdatasession ALTER COLUMN scope_type SET DEFAULT 'org'",
            reverse_sql="ALTER TABLE ddpui_chatwithdatasession ALTER COLUMN scope_type DROP DEFAULT",
        ),
    ]
