# Generated by Django 4.2 on 2026-07-22 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0170_orgusergroup_orgusergroupmember_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource_type", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=255)),
                (
                    "principal_type",
                    models.CharField(choices=[("user", "User"), ("group", "Group")], max_length=5),
                ),
                ("principal_id", models.BigIntegerField()),
                (
                    "access_level",
                    models.CharField(choices=[("view", "View"), ("edit", "Edit")], max_length=5),
                ),
                ("pending_email", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_shares_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
            ],
            options={
                "db_table": "resource_share",
            },
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["org", "resource_type", "resource_id"], name="resource_sh_org_id_d2b47f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["org", "principal_type", "principal_id"],
                name="resource_sh_org_id_1ff3b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(fields=["pending_email"], name="resource_sh_pending_df14fb_idx"),
        ),
    ]
