# Generated by Django 4.2 on 2026-08-18 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0169_chat_with_data_table_cards"),
        ("ddpui", "0171_orgwarehouse_org_unique"),
    ]

    operations = []
