# Generated by Django 4.2 on 2026-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0171_resourceshare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgpreferences",
            name="allow_public_sharing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_analyst_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit"), ("no_access", "No Access")],
                default="view",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_member_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit"), ("no_access", "No Access")],
                default="view",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="resourceshare",
            name="access_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit"), ("no_access", "No Access")],
                max_length=10,
            ),
        ),
    ]
