# Generated by Django 4.2 on 2026-07-16 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0168_alter_alert_created_by_alter_chart_created_by_and_more"),
        ("ddpui", "0171_chat_session_scope"),
    ]

    operations = []
