# Generated by Django 4.2 on 2026-07-10 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0171_seed_share_permission_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_groups_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_groups",
                        to="ddpui.org",
                    ),
                ),
            ],
            options={
                "db_table": "user_group",
            },
        ),
        migrations.CreateModel(
            name="UserGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("pending_email", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("pending", "Pending")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="ddpui.usergroup",
                    ),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_group_memberships",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "user_group_member",
            },
        ),
        migrations.AddConstraint(
            model_name="usergroupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "orguser"), name="uq_user_group_member_orguser"
            ),
        ),
        migrations.AddConstraint(
            model_name="usergroupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "pending_email"), name="uq_user_group_member_pending_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="usergroupmember",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("orguser__isnull", False), ("pending_email__isnull", True)),
                    models.Q(("orguser__isnull", True), ("pending_email__isnull", False)),
                    _connector="OR",
                ),
                name="ck_user_group_member_exactly_one_principal",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergroup",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="uq_user_group_org_name"
            ),
        ),
    ]
