# Generated by Django 4.2 on 2026-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0172_merge_20260818_0409"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwithdataorgconfig",
            name="pii_rules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
