# Generated by Django 4.2 on 2026-08-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0173_orgtask_post_sync_transform"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="trial_walkthrough",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
