# Generated by Django 4.2 on 2026-07-10 19:33

import ddpui.models.org_user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0173_seed_user_group_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(default=ddpui.models.org_user.default_invitation_expiry),
        ),
    ]
