# Generated by Django 4.2 on 2026-07-12 14:32

import ddpui.models.access_request
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0174_invitation_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource_type", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=255)),
                ("requested_permission", models.CharField(max_length=5)),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=ddpui.models.access_request.default_access_request_expiry
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests_decided",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests_made",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "access_request",
            },
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="access_requ_resourc_9feb10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(fields=["org", "status"], name="access_requ_org_id_7480f9_idx"),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(fields=["requester"], name="access_requ_request_b658ce_idx"),
        ),
    ]
