# Generated by Django 4.2 on 2026-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0174_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="trial_emails_sent",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="trial_walkthrough",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
