# Generated by Django 4.2 on 2026-08-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0175_resource_sharing"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource_type", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=255)),
                (
                    "requested_level",
                    models.CharField(choices=[("view", "View"), ("edit", "Edit")], max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "access_request",
            },
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["org", "resource_type", "resource_id"], name="access_req_org_resource_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("org", "resource_type", "resource_id", "requester"),
                name="uq_access_request_pending_per_user",
            ),
        ),
    ]
