# Generated by Django 4.2 on 2026-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0175_access_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
