# Generated by Django 4.2 on 2026-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0175_userpreferences_trial_walkthrough_and_emails_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.CharField(db_index=True, max_length=254)),
                ("org_name", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("signed_up_at", models.DateTimeField()),
                ("tnc_accepted", models.BooleanField(default=False)),
                ("trial_start_date", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-signed_up_at"],
            },
        ),
    ]
