# Generated by Django 4.2 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    """Store persistent top-left coordinates for UI4T canvas nodes."""

    dependencies = [
        ("ddpui", "0176_trialsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvasnode",
            name="position_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="canvasnode",
            name="position_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
