# Generated by Django 4.2 on 2026-08-18 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0176_trialsignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="ddpui.orguser"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_groups",
                        to="ddpui.org",
                    ),
                ),
            ],
            options={
                "db_table": "orguser_group",
            },
        ),
        migrations.AddField(
            model_name="chart",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kpi",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="allow_public_sharing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_analyst_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit"), ("no_access", "No Access")],
                default="edit",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="orgpreferences",
            name="default_member_level",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit"), ("no_access", "No Access")],
                default="view",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reportsnapshot",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ResourceShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource_type", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=255)),
                (
                    "principal_type",
                    models.CharField(
                        choices=[("user", "User"), ("group", "Group")], max_length=5, null=True
                    ),
                ),
                ("principal_id", models.BigIntegerField(null=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[("view", "View"), ("edit", "Edit"), ("no_access", "No Access")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_shares_created",
                        to="ddpui.orguser",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.invitation",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ddpui.resourceshare",
                    ),
                ),
            ],
            options={
                "db_table": "resource_share",
            },
        ),
        migrations.CreateModel(
            name="OrgUserGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="ddpui.orgusergroup",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ddpui.invitation",
                    ),
                ),
                (
                    "orguser",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="ddpui.orguser"
                    ),
                ),
            ],
            options={
                "db_table": "orguser_group_member",
            },
        ),
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource_type", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=255)),
                (
                    "requested_level",
                    models.CharField(choices=[("view", "View"), ("edit", "Edit")], max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ddpui.org"),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "access_request",
            },
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["org", "resource_type", "resource_id"], name="resource_sh_org_id_d2b47f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(
                fields=["org", "principal_type", "principal_id"],
                name="resource_sh_org_id_1ff3b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceshare",
            index=models.Index(fields=["parent"], name="resource_sh_parent_idx"),
        ),
        migrations.AddConstraint(
            model_name="resourceshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("org", "resource_type", "resource_id", "principal_type", "principal_id"),
                name="uq_resource_share_direct_grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=(
                    "org",
                    "resource_type",
                    "resource_id",
                    "principal_type",
                    "principal_id",
                    "parent",
                ),
                name="uq_resource_share_cascade_grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgusergroupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "invitation"), name="uq_orguser_group_member_invitation"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["org", "resource_type", "resource_id"], name="access_req_org_resource_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("org", "resource_type", "resource_id", "requester"),
                name="uq_access_request_pending_per_user",
            ),
        ),
    ]
