# Generated by Django 4.2 on 2026-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0176_trialsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialsignup",
            name="tnc_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
