# Generated by Django 4.2 on 2026-08-28 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0173_chatwithdataorgconfig_pii_rules"),
        ("ddpui", "0176_trialsignup"),
    ]

    operations = []
