# Generated by Django 4.2 on 2026-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0177_orgusergroup_chart_is_private_dashboard_is_private_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="enable_schema_change_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
