# Generated by Django 4.2 on 2026-07-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0177_per_role_general_access_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgpreferences",
            name="default_analyst_level",
            field=models.CharField(
                choices=[("none", "None"), ("view", "View"), ("edit", "Edit")],
                default="view",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="orgpreferences",
            name="default_member_level",
            field=models.CharField(
                choices=[("none", "None"), ("view", "View"), ("edit", "Edit")],
                default="view",
                max_length=5,
            ),
        ),
    ]
