# Generated by Django 4.2 on 2026-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0177_invitation_invited_in_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="send_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="send_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_org_ids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
