# Generated by Django 4.2 on 2026-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0178_userpreferences_enable_schema_change_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="enable_email_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
