# Generated by Django 4.2 on 2026-08-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0179_alter_userpreferences_enable_email_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orguser",
            name="has_seen_rbac_notice",
        ),
        migrations.AddField(
            model_name="orguser",
            name="has_seen_resource_sharing_notice",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has seen the one-time resource-sharing introduction carousel",
            ),
        ),
    ]
