# Generated by Django 4.2 on 2026-09-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0180_remove_orguser_has_seen_rbac_notice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("chart", "Chart"),
                            ("report", "Report"),
                            ("kpi", "KPI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="ddpui.orguser",
                    ),
                ),
            ],
            options={
                "db_table": "favorite",
            },
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="favorite_resourc_ad1413_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("org_user", "resource_type", "resource_id"), name="unique_favorite"
            ),
        ),
    ]
