# Generated by Django 4.2 on 2026-09-07 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0177_merge_20260828_1526"),
        ("ddpui", "0181_favorite"),
    ]

    operations = []
