# Generated by Django 4.2 on 2026-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0181_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="dependent_group_filter_ids",
            field=models.JSONField(default=list),
        ),
    ]
