# Generated by Django 4.2 on 2026-09-08 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0182_merge_0177_merge_20260828_1526_0181_favorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatWithDataTableCard",
        ),
    ]
