# Generated by Django 4.2 on 2026-09-30 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddpui', '0183_copilot_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatwithdataorgconfig',
            name='memory_text',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AddField(
            model_name='chatwithdataorgconfig',
            name='memory_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatwithdataorgconfig',
            name='memory_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ddpui.orguser'),
        ),
        migrations.DeleteModel(
            name='ChatWithDataOrgMemory',
        ),
    ]
