# Generated by Django 4.2 on 2026-09-08 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddpui', '0183_remove_unused_chat_table_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWithDataOrgMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_with_data_memory', to='ddpui.org')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ddpui.orguser')),
            ],
        ),
    ]
