# Generated by Django 4.2 on 2026-10-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0184_merge_org_memory_into_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgpreferences",
            name="auto_accept_non_breaking_schema_changes",
            field=models.BooleanField(default=False),
        ),
    ]
