# Generated by Django 4.2 on 2026-09-17 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0185_copilot_settings_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatwithdataorgconfig",
            name="pii_rules",
        ),
    ]
