# Generated by Django 4.2 on 2026-10-07 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0185_orgpreferences_auto_accept_non_breaking_schema_changes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgschemachange",
            name="schedule_job",
        ),
    ]
