# Generated by Django 4.2 on 2026-10-07 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0186_remove_orgschemachange_schedule_job"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConnectionJob",
        ),
    ]
