# Generated by Django 4.2 on 2026-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0187_delete_connectionjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("execute", "Execute"),
                    ("share", "Share"),
                    ("export", "Export"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("password_changed", "Password Changed"),
                    ("email_verified", "Email Verified"),
                    ("schema_change_auto_accepted", "Schema Change Auto Accepted"),
                ],
                max_length=50,
            ),
        ),
    ]
