# Generated by Django 4.2 on 2026-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0188_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardfilter",
            name="dependent_group_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
