"""Test SQL Query Generation for Multiple Dimensions and Metrics

Tests that verify the SQL queries generated by build_chart_query and build_multi_metric_query
correctly include all dimensions and metrics in SELECT and GROUP BY clauses.
"""

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ddpui.settings")
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
django.setup()

import pytest
from unittest.mock import MagicMock, patch
from sqlalchemy import text
from ddpui.core.charts import charts_service
from ddpui.core.charts.query_builder import AggQueryBuilder
from ddpui.schemas.chart_schema import ChartDataPayload, ChartMetric
from ddpui.models.org import OrgWarehouse

pytestmark = pytest.mark.django_db


class TestQueryGenerationMultipleDimensions:
    """Tests for SQL query generation with multiple dimensions"""

    def test_query_two_dimensions_one_metric(self):
        """Test query generation with 2 dimensions and 1 metric"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "region"],
            metrics=[ChartMetric(aggregation="count", column=None, alias="Total Count")],
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        # Get the compiled SQL query
        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_query_two_dimensions_one_metric ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Verify both dimensions are in SELECT
        assert "KEY" in compiled_query or "key" in compiled_query.lower()
        assert "region" in compiled_query or "region" in compiled_query.lower()

        # Verify metric is in SELECT
        assert "count" in compiled_query.lower()

        # Verify GROUP BY includes both dimensions
        assert "GROUP BY" in compiled_query.upper() or "group by" in compiled_query.lower()

        # Count GROUP BY columns - should have at least 2
        group_by_section = (
            compiled_query.upper().split("GROUP BY")[-1]
            if "GROUP BY" in compiled_query.upper()
            else ""
        )
        # Should have both dimensions in GROUP BY
        assert "KEY" in group_by_section or "key" in group_by_section.lower()
        assert "region" in group_by_section or "region" in group_by_section.lower()

    def test_query_three_dimensions_two_metrics(self):
        """Test query generation with 3 dimensions and 2 metrics"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "region", "country"],
            metrics=[
                ChartMetric(aggregation="count", column=None, alias="Total Count"),
                ChartMetric(aggregation="sum", column="revenue", alias="Revenue"),
            ],
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_query_three_dimensions_two_metrics ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Verify all 3 dimensions are in SELECT
        assert "KEY" in compiled_query or "key" in compiled_query.lower()
        assert "region" in compiled_query or "region" in compiled_query.lower()
        assert "country" in compiled_query or "country" in compiled_query.lower()

        # Verify both metrics are in SELECT
        assert "count" in compiled_query.lower()
        assert "sum" in compiled_query.lower() or "SUM" in compiled_query
        assert "revenue" in compiled_query.lower()

        # Verify GROUP BY includes all 3 dimensions
        group_by_section = (
            compiled_query.upper().split("GROUP BY")[-1]
            if "GROUP BY" in compiled_query.upper()
            else ""
        )
        assert "KEY" in group_by_section or "key" in group_by_section.lower()
        assert "region" in group_by_section or "region" in group_by_section.lower()
        assert "country" in group_by_section or "country" in group_by_section.lower()

    def test_query_four_dimensions_three_metrics(self):
        """Test query generation with 4 dimensions and 3 metrics"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "region", "country", "state"],
            metrics=[
                ChartMetric(aggregation="count", column=None, alias="Total Count"),
                ChartMetric(aggregation="sum", column="revenue", alias="Revenue"),
                ChartMetric(aggregation="avg", column="price", alias="Average Price"),
            ],
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_query_four_dimensions_three_metrics ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Verify all 4 dimensions are in SELECT
        assert "KEY" in compiled_query or "key" in compiled_query.lower()
        assert "region" in compiled_query or "region" in compiled_query.lower()
        assert "country" in compiled_query or "country" in compiled_query.lower()
        assert "state" in compiled_query or "state" in compiled_query.lower()

        # Verify all 3 metrics are in SELECT
        assert "count" in compiled_query.lower()
        assert "sum" in compiled_query.lower() or "SUM" in compiled_query
        assert (
            "avg" in compiled_query.lower()
            or "AVG" in compiled_query
            or "average" in compiled_query.lower()
        )
        assert "revenue" in compiled_query.lower()
        assert "price" in compiled_query.lower()

        # Verify GROUP BY includes all 4 dimensions
        group_by_section = (
            compiled_query.upper().split("GROUP BY")[-1]
            if "GROUP BY" in compiled_query.upper()
            else ""
        )
        assert "KEY" in group_by_section or "key" in group_by_section.lower()
        assert "region" in group_by_section or "region" in group_by_section.lower()
        assert "country" in group_by_section or "country" in group_by_section.lower()
        assert "state" in group_by_section or "state" in group_by_section.lower()

    def test_query_dimensions_only_no_metrics(self):
        """Test query generation with dimensions only (no metrics)"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "region", "country"],
            metrics=None,
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_query_dimensions_only_no_metrics ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Verify all 3 dimensions are in SELECT
        assert "KEY" in compiled_query or "key" in compiled_query.lower()
        assert "region" in compiled_query or "region" in compiled_query.lower()
        assert "country" in compiled_query or "country" in compiled_query.lower()

        # Verify no GROUP BY (non-aggregated query)
        # For non-aggregated queries, there should be no GROUP BY
        assert "GROUP BY" not in compiled_query.upper() or "group by" not in compiled_query.lower()


class TestQueryBuilderMultipleDimensions:
    """Tests for AggQueryBuilder with multiple dimensions"""

    def test_build_multi_metric_query_adds_all_dimensions(self):
        """Test that build_multi_metric_query adds all dimensions to query builder"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "region", "country"],
            metrics=[
                ChartMetric(aggregation="count", column=None),
                ChartMetric(aggregation="sum", column="revenue"),
            ],
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = AggQueryBuilder()
        query_builder.fetch_from(payload.table_name, payload.schema_name)

        result = charts_service.build_multi_metric_query(payload, query_builder, mock_warehouse)

        # Verify query builder was modified
        assert result is not None

        # Get compiled query to verify structure
        compiled_query = str(result.compile())
        print(f"\n=== TEST: test_build_multi_metric_query_adds_all_dimensions ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Verify dimensions are in SELECT
        assert "KEY" in compiled_query or "key" in compiled_query.lower()
        assert "region" in compiled_query or "region" in compiled_query.lower()
        assert "country" in compiled_query or "country" in compiled_query.lower()

        # Verify metrics are in SELECT
        assert "count" in compiled_query.lower()
        assert "sum" in compiled_query.lower() or "SUM" in compiled_query
        assert "revenue" in compiled_query.lower()

    def test_query_builder_labels_dimensions_correctly(self):
        """Test that dimension columns are labeled correctly for data access"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "region"],
            metrics=[ChartMetric(aggregation="count", column=None, alias="Total Count")],
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        # Verify query builder has columns with labels
        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_query_builder_labels_dimensions_correctly ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Labels ensure we can access columns by their original names
        # Check that dimensions appear in the query (they should be labeled)
        assert "KEY" in compiled_query or "key" in compiled_query.lower()
        assert "region" in compiled_query or "region" in compiled_query.lower()


class TestQueryGenerationEdgeCases:
    """Tests for edge cases in query generation"""

    def test_query_filters_empty_dimensions(self):
        """Test that empty dimension strings are filtered out"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "", "region", "   "],
            metrics=[ChartMetric(aggregation="count", column=None)],
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_query_filters_empty_dimensions ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Should only have KEY and region, not empty strings
        assert "KEY" in compiled_query or "key" in compiled_query.lower()
        assert "region" in compiled_query or "region" in compiled_query.lower()

        # Empty strings should not appear as column names
        # (check that we don't have empty GROUP BY clauses)

    def test_query_with_time_grain_and_multiple_dimensions(self):
        """Test query generation with time grain and multiple dimensions"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["date_column", "region"],
            metrics=[ChartMetric(aggregation="sum", column="revenue")],
            extra_config={"time_grain": "day"},
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_query_with_time_grain_and_multiple_dimensions ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Verify time grain is applied to date_column
        # PostgreSQL uses DATE_TRUNC for time grain
        assert "DATE_TRUNC" in compiled_query.upper() or "date_trunc" in compiled_query.lower()

        # Verify region is still included
        assert "region" in compiled_query.lower()

        # Verify GROUP BY includes both time grain expression and region
        group_by_section = (
            compiled_query.upper().split("GROUP BY")[-1]
            if "GROUP BY" in compiled_query.upper()
            else ""
        )
        assert "region" in group_by_section.lower() or "REGION" in group_by_section


class TestQueryColumnOrdering:
    """Tests for column ordering in generated queries"""

    def test_dimensions_before_metrics_in_select(self):
        """Test that dimensions appear before metrics in SELECT clause"""
        payload = ChartDataPayload(
            chart_type="table",
            schema_name="public",
            table_name="test_table",
            dimensions=["KEY", "region"],
            metrics=[
                ChartMetric(aggregation="count", column=None, alias="Total Count"),
                ChartMetric(aggregation="sum", column="revenue", alias="Revenue"),
            ],
        )

        mock_warehouse = MagicMock(spec=OrgWarehouse)
        mock_warehouse.wtype = "postgres"

        query_builder = charts_service.build_chart_query(payload, mock_warehouse)

        compiled_query = str(query_builder.compile())
        print(f"\n=== TEST: test_dimensions_before_metrics_in_select ===")
        print(f"Compiled Query:\n{compiled_query}\n")

        # Find SELECT clause
        select_section = (
            compiled_query.upper().split("SELECT")[-1].split("FROM")[0]
            if "SELECT" in compiled_query.upper()
            else ""
        )

        # Dimensions should appear before metrics in the SELECT clause
        # Check that KEY appears before count
        key_index = (
            select_section.find("KEY")
            if "KEY" in select_section
            else select_section.lower().find("key")
        )
        count_index = select_section.lower().find("count")

        if key_index != -1 and count_index != -1:
            assert key_index < count_index, "Dimensions should appear before metrics in SELECT"
