version = 1
test_patterns = [
  "ddpui/tests/**",
  "scripts/test*.py"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 200
  cyclomatic_complexity_threshold = "high"