# prefect block names (they come from prefect's block_type table)
AIRBYTESERVER = "Airbyte Server"
AIRBYTECONNECTION = "Airbyte Connection"
SHELLOPERATION = "Shell Operation"
DBTCORE = "dbt Core Operation"
DBTCLOUDJOB = "dbt Cloud Job"
DBTCLOUDCREDS = "dbt Cloud Credentials"
DBTCLIPROFILE = "dbt CLI Profile"
SECRET = "Secret"

# Prefect flow run status types
# terminal
FLOW_RUN_FAILED_STATE_TYPE = "FAILED"
FLOW_RUN_COMPLETED_STATE_TYPE = "COMPLETED"
FLOW_RUN_CRASHED_STATE_TYPE = "CRASHED"
FLOW_RUN_CANCELLED_STATE_TYPE = "CANCELLED"
# non-terminal
FLOW_RUN_SCHEDULED_STATE_TYPE = "SCHEDULED"
FLOW_RUN_PENDING_STATE_TYPE = "PENDING"
FLOW_RUN_RUNNING_STATE_TYPE = "RUNNING"

FLOW_RUN_TERMINAL_STATE_TYPES = [
    FLOW_RUN_FAILED_STATE_TYPE,
    FLOW_RUN_COMPLETED_STATE_TYPE,
    FLOW_RUN_CRASHED_STATE_TYPE,
    FLOW_RUN_CANCELLED_STATE_TYPE,
]

# Prefect flow run status names
# terminal
FLOW_RUN_FAILED_STATE_NAME = "Failed"
FLOW_RUN_COMPLETED_STATE_NAME = "Completed"
FLOW_RUN_CRASHED_STATE_NAME = "Crashed"
FLOW_RUN_CANCELLED_STATE_NAME = "Cancelled"
# non-terminal
FLOW_RUN_SCHEDULED_STATE_NAME = "Scheduled"
FLOW_RUN_PENDING_STATE_NAME = "Pending"
FLOW_RUN_RUNNING_STATE_NAME = "Running"

# Map state_name to states
MAP_FLOW_RUN_STATE_NAME_TO_TYPE = {
    FLOW_RUN_FAILED_STATE_NAME: FLOW_RUN_FAILED_STATE_TYPE,
    FLOW_RUN_COMPLETED_STATE_NAME: FLOW_RUN_COMPLETED_STATE_TYPE,
    FLOW_RUN_CRASHED_STATE_NAME: FLOW_RUN_CRASHED_STATE_TYPE,
    FLOW_RUN_CANCELLED_STATE_NAME: FLOW_RUN_CANCELLED_STATE_TYPE,
    FLOW_RUN_SCHEDULED_STATE_NAME: FLOW_RUN_SCHEDULED_STATE_TYPE,
    FLOW_RUN_PENDING_STATE_NAME: FLOW_RUN_PENDING_STATE_TYPE,
    FLOW_RUN_RUNNING_STATE_NAME: FLOW_RUN_RUNNING_STATE_TYPE,
    "DBT_TEST_FAILED": FLOW_RUN_COMPLETED_STATE_TYPE,
}


# Prefect worker related
DDP_WORK_QUEUE = "ddp"
MANUL_DBT_WORK_QUEUE = "manual-dbt"
BOOTCAMP_DDP_QUEUE = "bootcamp-ddp"

# Kind
FLOW_RUN_KIND = "flow-run"
TASK_RUN_KIND = "task-run"
