"""
Django settings for ddpui project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
import sentry_sdk

from corsheaders.defaults import default_headers
from dotenv import load_dotenv
from ddpui.utils.ddp_logger import setup_logger as setup_ddp_logger
from ddpui.utils.ab_logger import setup_logger as setup_ab_logger
import ddpui.utils.flags  # pylint: disable=unused-import

load_dotenv()

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=float(os.getenv("SENTRY_TSR", "1.0")),
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=float(os.getenv("SENTRY_PSR", "1.0")),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGOSECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "") == "True"


# CORS

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "staging-api.dalgo.in",
    "api.dalgo.in",
    "staging.dalgo.in",
    "dashboard.dalgo.in",
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]
CORS_ORIGIN_WHITELIST = (
    "http://localhost:3000",
    "http://host.docker.internal:3000",
    "http://127.0.0.1:3000",
    "https://staging.dalgo.in",
    "https://dashboard.dalgo.in",
)
CORS_ALLOW_HEADERS = (*default_headers, "x-dalgo-org")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "ddpui",
    "django_prometheus",
    "django_extensions",
    "channels",
    "flags",
]

# Feature flags
# AIRBYTE_PROFILE: to get airbyte credentials through prefect block
# LOG_SUMMARY: allow summarizing logs through open AI
# AIRBYTE_RESET_JOB: to reset airbyte connection
FLAGS = {"AIRBYTE_PROFILE": [], "LOG_SUMMARY": [], "AIRBYTE_RESET_JOB": []}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "ddpui.auth.BearerAuthentication",
    ]
}

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "ddpui.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ddpui.wsgi.application"

ASGI_APPLICATION = "ddpui.asgi.application"  # for websockets


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("REDIS_HOST", "localhost"), os.getenv("REDIS_PORT", "6379"))]
        },
    }
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DBNAME"),
        "HOST": os.getenv("DBHOST"),
        "USER": os.getenv("DBUSER"),
        "PASSWORD": os.getenv("DBPASSWORD"),
        "PORT": os.getenv("DBPORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# custom airbyte connectors
AIRBYTE_CUSTOM_SOURCES = {
    "tech4dev/source-kobotoolbox": {
        "name": "KoboToolbox",
        "docker_repository": "tech4dev/source-kobotoolbox",
        "docker_image_tag": "0.2.0",
        "documentation_url": "",
    },
    "tech4dev/source-commcare": {
        "name": "CommCare T4D",
        "docker_repository": "tech4dev/source-commcare",
        "docker_image_tag": "0.1.0",
        "documentation_url": "",
    },
    "tech4dev/source-avni": {
        "name": "Avni",
        "docker_repository": "tech4dev/source-avni",
        "docker_image_tag": "0.1.0",
        "documentation_url": "",
    },
    "tech4dev/source-papersurvey": {
        "name": "PaperSurvey",
        "docker_repository": "tech4dev/source-papersurvey",
        "docker_image_tag": "0.1.1",
        "documentation_url": "",
    },
    "tech4dev/source-glific": {
        "name": "Glific",
        "docker_repository": "tech4dev/source-glific",
        "docker_image_tag": "0.1.0",
        "documentation_url": "",
    },
    "dhwaniris/airbyte-greythr-connector": {
        "name": "greytHR",
        "docker_repository": "dhwaniris/airbyte-greythr-connector",
        "docker_image_tag": "1.0.4",
        "documentation_url": "",
    },
}

AIRBYTE_SOURCE_BLACKLIST = [
    "airbyte/source-commcare",
]

# finally set up the loggers
setup_ddp_logger()
setup_ab_logger()


# Fixtures to seed data
# python3 manage.py loaddata seed/tasks.json
FIXTURE_DIRS = [
    "seed",
]

PRODUCTION = os.getenv("PRODUCTION", "") == "True"
