"""Chart schemas — split into customizations, config (with shared sub-schemas), crud, data, geojson."""

from ddpui.schemas.chart_schemas.config import (
    BarChartConfig,
    ChartExtraConfig,
    ChartFilter,
    ChartMetric,
    ChartMetricAggregation,
    ChartPagination,
    ChartSort,
    FilterOperator,
    LineChartConfig,
    MapChartConfig,
    NumberChartConfig,
    PieChartConfig,
    TableChartConfig,
    TableChartDimension,
    _CHART_CONFIG_BY_TYPE,
    _ChartConfigBase,
)
from ddpui.schemas.chart_schemas.crud import (
    ChartConfig,
    ChartCreate,
    ChartResponse,
    ChartUpdate,
)
from ddpui.schemas.chart_schemas.customizations import (
    AxisLabelRotation,
    BarChartCustomizations,
    CardinalLegendPosition,
    ColumnDateFormat,
    ColumnNumberFormat,
    DateFormat,
    LegendDisplay,
    LineChartCustomizations,
    MapChartCustomizations,
    MapColorScheme,
    MapLegendPosition,
    NumberChartCustomizations,
    NumberFormat,
    PieChartCustomizations,
    TableChartCustomizations,
)
from ddpui.schemas.chart_schemas.data import (
    ChartDataPayload,
    ChartDataResponse,
    DataPreviewResponse,
    ExecuteChartQuery,
    TransformDataForChart,
)
from ddpui.schemas.chart_schemas.geojson import (
    GeoJSONDetailResponse,
    GeoJSONListResponse,
    GeoJSONUpload,
)

__all__ = [
    # config + shared sub-schemas
    "ChartMetric",
    "ChartMetricAggregation",
    "ChartFilter",
    "ChartSort",
    "ChartPagination",
    "FilterOperator",
    "TableChartDimension",
    "BarChartConfig",
    "LineChartConfig",
    "PieChartConfig",
    "NumberChartConfig",
    "MapChartConfig",
    "TableChartConfig",
    "ChartExtraConfig",
    "_ChartConfigBase",
    "_CHART_CONFIG_BY_TYPE",
    # customizations
    "NumberFormat",
    "DateFormat",
    "LegendDisplay",
    "CardinalLegendPosition",
    "MapLegendPosition",
    "AxisLabelRotation",
    "MapColorScheme",
    "ColumnNumberFormat",
    "ColumnDateFormat",
    "BarChartCustomizations",
    "LineChartCustomizations",
    "PieChartCustomizations",
    "NumberChartCustomizations",
    "MapChartCustomizations",
    "TableChartCustomizations",
    # crud
    "ChartCreate",
    "ChartUpdate",
    "ChartResponse",
    "ChartConfig",
    # data
    "ChartDataPayload",
    "ChartDataResponse",
    "DataPreviewResponse",
    "ExecuteChartQuery",
    "TransformDataForChart",
    # geojson
    "GeoJSONListResponse",
    "GeoJSONDetailResponse",
    "GeoJSONUpload",
]
