# Generated by Django 4.1.7 on 2023-03-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0003_clientdbt_remove_org_dbt_repo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="slug",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
