# Generated by Django 4.1.7 on 2023-03-31 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0004_org_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgPrefectBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocktype", models.CharField(max_length=25)),
                ("blockid", models.CharField(max_length=36, unique=True)),
                ("blockname", models.CharField(max_length=100, unique=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddpui.org",
                    ),
                ),
            ],
        ),
    ]
